#!/usr/bin/env bash
# Regenerate TypeScript bindings from the Rust proto/server structs via ts-rs.
#
#   webui/scripts/gen-bindings.sh
#
# Run from anywhere; resolves the repo root itself. Emits flat *.ts files into
# webui/src/lib/bindings/ plus an index.ts barrel.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out="$repo_root/webui/src/lib/bindings"
staging="$(dirname "$out")/.bindings.staging.$$"

count_ts() { find "$1" -maxdepth 1 -name '*.ts' 2>/dev/null | wc -l; }

before="$(count_ts "$out")"

# Loud and last, so it survives the habitual `2>&1 | tail -5`.
on_exit() {
  local code=$?
  rm -rf "$staging"
  if [ "$code" -ne 0 ]; then
    {
      echo
      echo "!!!! gen-bindings.sh FAILED (exit $code)"
      echo "!!!! $out was NOT modified — $before binding file(s) still in place."
    } >&2
  fi
}
trap on_exit EXIT
trap 'exit 130' INT
trap 'exit 143' TERM HUP

# A SIGKILL leaves no chance to clean up, so sweep whatever an earlier run left.
for stale in "$(dirname "$out")"/.bindings.staging.*; do
  [ -d "$stale" ] || continue
  rm -rf "$stale"
done

mkdir -p "$staging"

# ts-rs writes one file per #[ts(export)] type, relative to TS_RS_EXPORT_DIR.
TS_RS_EXPORT_DIR="$staging" cargo test --manifest-path "$repo_root/Cargo.toml" \
  -p cctui-proto -p cctui-server export_bindings

generated="$(count_ts "$staging")"
if [ "$generated" -eq 0 ]; then
  echo "gen-bindings.sh: cargo produced no binding files" >&2
  exit 1
fi
if [ "$before" -gt 0 ] && [ "$generated" -lt $((before / 2)) ]; then
  echo "gen-bindings.sh: only $generated binding file(s) generated, down from $before." >&2
  echo "  Refusing the swap. Re-run with CCTUI_BINDINGS_ALLOW_SHRINK=1 if intended." >&2
  [ "${CCTUI_BINDINGS_ALLOW_SHRINK:-}" = "1" ] || exit 1
fi

# ts-rs maps Rust 64-bit ints (i64/u64) to `bigint`, but these are JSON numbers
# at runtime (token counts, uptime — always within Number.MAX_SAFE_INTEGER), so
# JSON.parse yields a JS `number`. Normalize the type to match runtime.
find "$staging" -name '*.ts' -exec sed -i 's/\bbigint\b/number/g' {} +

# Barrel re-export so the UI can `import { Foo } from '@bindings'`.
{
  echo "// AUTO-GENERATED by webui/scripts/gen-bindings.sh — do not edit."
  for f in "$staging"/*.ts; do
    base="$(basename "$f" .ts)"
    [ "$base" = "index" ] && continue
    echo "export type * from './$base';"
  done
} > "$staging/index.ts"

rm -rf "$out"
mv "$staging" "$out"

echo "Generated $(ls "$out"/*.ts | wc -l) binding files into $out"
