#!/usr/bin/env bash
# Regenerate TypeScript bindings from the Rust proto/server structs via ts-rs.
#
#   webui/scripts/gen-bindings.sh
#
# Run from anywhere; resolves the repo root itself. Emits flat *.ts files into
# webui/src/lib/bindings/ plus an index.ts barrel.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out="$repo_root/webui/src/lib/bindings"

rm -rf "$out"
mkdir -p "$out"

# ts-rs writes one file per #[ts(export)] type, relative to TS_RS_EXPORT_DIR.
TS_RS_EXPORT_DIR="$out" cargo test --manifest-path "$repo_root/Cargo.toml" \
  -p cctui-proto -p cctui-server export_bindings

# ts-rs maps Rust 64-bit ints (i64/u64) to `bigint`, but these are JSON numbers
# at runtime (token counts, uptime — always within Number.MAX_SAFE_INTEGER), so
# JSON.parse yields a JS `number`. Normalize the type to match runtime.
find "$out" -name '*.ts' -exec sed -i 's/\bbigint\b/number/g' {} +

# Barrel re-export so the UI can `import { Foo } from '@bindings'`.
{
  echo "// AUTO-GENERATED by webui/scripts/gen-bindings.sh — do not edit."
  for f in "$out"/*.ts; do
    base="$(basename "$f" .ts)"
    [ "$base" = "index" ] && continue
    echo "export type * from './$base';"
  done
} > "$out/index.ts"

echo "Generated $(ls "$out"/*.ts | wc -l) binding files into $out"
