-- GH-UI-1: the attention-bucket derivation (GH-CONN-6) needs to know which PRs
-- the connector's identity authored vs. is review-requested on. The reconcile
-- poll (GH-CONN-4) only stores PRs that "involve me", but nothing recorded *who*
-- "me" is. Cache the connector credential's GitHub login here so the inbox
-- endpoint can split authored (`pull.author == viewer_login`) from
-- review-requested without a per-request GitHub call.
--
-- Nullable: a connector that has not completed a reconcile pass yet has no
-- known login. The inbox falls back to a viewer-less derivation (everything
-- not closed/merged is `Waiting`) until the first pass fills it in.
ALTER TABLE connectors ADD COLUMN viewer_login TEXT;
