-- no-transaction
--
-- The free-text predicate is a per-session `EXISTS … WHERE e.session_id = s.id
-- AND left(e.search_text, 8192) ILIKE $p`. Served by the unscoped trgm index
-- (migration 065) the planner could only answer it by materialising every
-- matching event in the table and rechecking each one — 300k heap rechecks,
-- ~13 s, for a question whose answer is at most one row per session. Adding
-- session_id as a leading GIN key (btree_gin) lets the intersection happen in
-- the index, so a probe touches only the events of the session being tested.
--
-- The 8192 literal must match SEARCH_TEXT_CAP in routes/sessions.rs, exactly as
-- for migration 065 — the query's ILIKE runs against the same left() expression
-- so this index serves it only if the two agree.
--
-- CONCURRENTLY, and alone in its file: stream_events is multi-GB on an
-- established install, where a plain CREATE INDEX holds ACCESS EXCLUSIVE for
-- tens of minutes on the startup path, before the server binds its port. The
-- file must hold exactly one statement — Postgres runs a multi-statement simple
-- query in an implicit transaction block, which CONCURRENTLY refuses.
--
-- On a populated database build this out-of-band first, as for migration 065,
-- so IF NOT EXISTS makes this a no-op. A failed CONCURRENTLY build leaves an
-- INVALID index that IF NOT EXISTS will skip: check pg_index.indisvalid.
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_stream_events_session_search_trgm
    ON stream_events USING gin (session_id, left(search_text, 8192) gin_trgm_ops);
