#!/usr/bin/env python3
"""Setup script generated by cctui-server. Installs hooks for Claude Code."""
import json
import os
import stat
import subprocess

SERVER_URL = "__SERVER_URL__"
TOKEN = "__TOKEN__"

cctui_bin = os.path.expanduser("~/.cctui/bin")
os.makedirs(cctui_bin, exist_ok=True)

# --- Write bootstrap.sh (runs on SessionStart) ---
bootstrap_path = os.path.join(cctui_bin, "bootstrap.sh")
bootstrap_tpl = os.path.join(os.path.dirname(__file__), "bootstrap.sh.tpl") if "__file__" in dir() else None

# Download bootstrap.sh from server
subprocess.run(
    ["curl", "-sf", SERVER_URL + "/api/v1/scripts/bootstrap.sh", "-o", bootstrap_path],
    capture_output=True,
)
os.chmod(bootstrap_path, os.stat(bootstrap_path).st_mode | stat.S_IEXEC)
print(f"[cctui] wrote {bootstrap_path}")

# --- Download streamer.py ---
streamer_path = os.path.join(cctui_bin, "streamer.py")
subprocess.run(
    ["curl", "-sf", SERVER_URL + "/api/v1/scripts/streamer.py", "-o", streamer_path],
    capture_output=True,
)
os.chmod(streamer_path, os.stat(streamer_path).st_mode | stat.S_IEXEC)
print(f"[cctui] wrote {streamer_path}")

# --- Merge hooks into settings.json ---
settings_path = os.path.expanduser("~/.claude/settings.json")

hooks = {
    "SessionStart": [{"hooks": [{"type": "command", "command": bootstrap_path}]}],
    "PreToolUse": [
        {"hooks": [{"type": "http", "url": SERVER_URL + "/api/v1/check"}]}
    ],
}

if os.path.exists(settings_path):
    with open(settings_path) as f:
        settings = json.load(f)
    print(f"[cctui] merging hooks into {settings_path}")
else:
    settings = {}
    print(f"[cctui] creating {settings_path}")

settings["hooks"] = hooks

os.makedirs(os.path.dirname(settings_path), exist_ok=True)
with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2)

print(f"[cctui] done - sessions will register with {SERVER_URL}")
