#!/usr/bin/env python3
"""Setup script generated by cctui-server. Configures Claude Code to use cctui-channel."""
import json
import os
import shutil

SERVER_URL = os.environ.get("__SERVER_URL__", "__SERVER_URL__")
TOKEN = os.environ.get("__TOKEN__", "__TOKEN__")

# --- Find channel directory ---
channel_dir = os.environ.get(
    "CCTUI_CHANNEL_DIR",
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "channel"),
)

if not os.path.isdir(channel_dir):
    print(f"[cctui] ERROR: channel dir not found at {channel_dir}")
    print("        Set CCTUI_CHANNEL_DIR to the absolute path of the channel/ directory")
    exit(1)

# --- Write MCP server config to ~/.claude.json ---
claude_json_path = os.path.expanduser("~/.claude.json")

mcp_entry = {
    "command": shutil.which("bun") or os.path.expanduser("~/.bun/bin/bun"),
    "args": ["run", os.path.join(channel_dir, "src", "index.ts")],
    "env": {
        "CCTUI_URL": SERVER_URL,
        "CCTUI_AGENT_TOKEN": TOKEN,
    },
}

if os.path.exists(claude_json_path):
    with open(claude_json_path) as f:
        claude_config = json.load(f)
else:
    claude_config = {}

claude_config.setdefault("mcpServers", {})
claude_config["mcpServers"]["cctui"] = mcp_entry

with open(claude_json_path, "w") as f:
    json.dump(claude_config, f, indent=2)

print(f"[cctui] wrote MCP server config to {claude_json_path}")

# --- Merge hooks into settings.json ---
settings_path = os.path.expanduser("~/.claude/settings.json")

# SessionStart: pipe stdin through jq to inject $PPID and machine hostname, then POST to server
session_start_cmd = (
    f'jq -c --arg ppid "$PPID" --arg mid "$(hostname)" '
    f"'. + {{ppid: ($ppid | tonumber), machine_id: $mid}}' "
    f'| curl -sf -X POST {SERVER_URL}/api/v1/hooks/session-start '
    f"-H 'Content-Type: application/json' "
    f"-H 'Authorization: Bearer {TOKEN}' -d @-"
)

hooks = {
    "SessionStart": [{
        "hooks": [{
            "type": "command",
            "command": session_start_cmd,
        }],
    }],
    "PreToolUse": [{
        "hooks": [{
            "type": "http",
            "url": f"{SERVER_URL}/api/v1/check",
        }],
    }],
    "PostToolUse": [{
        "hooks": [{
            "type": "http",
            "url": f"{SERVER_URL}/api/v1/hooks/post-tool-use",
        }],
    }],
    "Stop": [{
        "hooks": [{
            "type": "http",
            "url": f"{SERVER_URL}/api/v1/hooks/stop",
        }],
    }],
}

if os.path.exists(settings_path):
    with open(settings_path) as f:
        settings = json.load(f)
    print(f"[cctui] merging hooks into {settings_path}")
else:
    settings = {}
    print(f"[cctui] creating {settings_path}")

settings["hooks"] = hooks

os.makedirs(os.path.dirname(settings_path), exist_ok=True)
with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2)

print(f"[cctui] done - hooks route to {SERVER_URL}")
print()
print("[cctui] IMPORTANT: To enable TUI→Claude messaging, start Claude with:")
print("        claude --dangerously-load-development-channels server:cctui")
print("        Without this flag, Claude sees the tools but won't receive channel messages.")
