#!/usr/bin/env python3
"""Setup script generated by cctui-server. Configures Claude Code to use cctui-channel."""
import json
import os
import shutil

SERVER_URL = os.environ.get("__SERVER_URL__", "__SERVER_URL__")
TOKEN = os.environ.get("__TOKEN__", "__TOKEN__")
HOOK_PORT = os.environ.get("__HOOK_PORT__", "8701")

# --- Find channel directory ---
channel_dir = os.environ.get(
    "CCTUI_CHANNEL_DIR",
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "channel"),
)

if not os.path.isdir(channel_dir):
    print(f"[cctui] ERROR: channel dir not found at {channel_dir}")
    print("        Set CCTUI_CHANNEL_DIR to the absolute path of the channel/ directory")
    exit(1)

# --- Write MCP server config to ~/.claude.json ---
claude_json_path = os.path.expanduser("~/.claude.json")

mcp_entry = {
    "command": shutil.which("bun") or os.path.expanduser("~/.bun/bin/bun"),
    "args": ["run", os.path.join(channel_dir, "src", "index.ts")],
    "env": {
        "CCTUI_URL": SERVER_URL,
        "CCTUI_AGENT_TOKEN": TOKEN,
        "CCTUI_HOOK_PORT": HOOK_PORT,
    },
}

if os.path.exists(claude_json_path):
    with open(claude_json_path) as f:
        claude_config = json.load(f)
else:
    claude_config = {}

claude_config.setdefault("mcpServers", {})
claude_config["mcpServers"]["cctui"] = mcp_entry

with open(claude_json_path, "w") as f:
    json.dump(claude_config, f, indent=2)

print(f"[cctui] wrote MCP server config to {claude_json_path}")

# --- Merge hooks into settings.json ---
settings_path = os.path.expanduser("~/.claude/settings.json")

hooks = {
    "SessionStart": [{
        "hooks": [{
            "type": "command",
            "command": f"curl -sf -X POST http://localhost:{HOOK_PORT}/hooks/session-start -H 'Content-Type: application/json' -d @-",
        }],
    }],
    "PreToolUse": [{
        "hooks": [{
            "type": "http",
            "url": f"http://localhost:{HOOK_PORT}/hooks/pre-tool-use",
        }],
    }],
}

if os.path.exists(settings_path):
    with open(settings_path) as f:
        settings = json.load(f)
    print(f"[cctui] merging hooks into {settings_path}")
else:
    settings = {}
    print(f"[cctui] creating {settings_path}")

settings["hooks"] = hooks

os.makedirs(os.path.dirname(settings_path), exist_ok=True)
with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2)

print(f"[cctui] done - Claude Code will use cctui-channel connecting to {SERVER_URL}")
