// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/v1/accounts/{id}/shares` payload. `user` is the grantee,
 * accepted as either a UUID or a login (`users.name`) so an operator can grant
 * by whichever they have. `action` defaults to `use` (the only action today).
 */
export type AccountGrantShare = { user: string, action?: string, };
