// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountModel } from "./AccountModel";
import type { RateLimits } from "./RateLimits";
import type { SoftLimitConfig } from "./SoftLimitConfig";
import type { UsageNotices } from "./UsageNotices";

/**
 * API view of one provider credential under an account. Secrets (the
 * OAuth/static tokens) are deliberately absent; `base_url`/`auth_scheme` are
 * surfaced so the accounts UI can render/edit a compatible endpoint in place.
 */
export type AccountProvider = { id: string, account_id: string, 
/**
 * `anthropic` | `openai` | `anthropic-compatible` | `openai-compatible`.
 */
provider: string, 
/**
 * Provider family (generated column): `anthropic` | `openai`. At most one
 * provider per family per account, guaranteed by construction.
 */
family: string, 
/**
 * Models this credential offers, declared by the operator, with optional
 * pricing. `None`/empty falls back to the harness catalog / native
 * families. Honoured for every provider kind.
 */
models: Array<AccountModel> | null, 
/**
 * Per-provider logical→concrete model alias map, e.g.
 * `{"opus": "claude-opus-4-8[1m]"}`. Resolved server-side at spawn.
 */
model_aliases: Record<string, string> | null, 
/**
 * `true` for a server-synthesized (managed) provider — read-only over the
 * API (the back-compat shim for `CCTUI_CLAUDE_LITELLM_*`).
 */
managed: boolean, 
/**
 * Compatible-endpoint base URL; NULL for native providers.
 */
base_url: string | null, 
/**
 * `oauth` (native) | `bearer` | `api_key` (compatible).
 */
auth_scheme: string, 
/**
 * Upstream account id (Codex `chatgpt_account_id`).
 */
provider_account_id: string | null, expires_at: string | null, created_at: string, last_used_at: string | null, request_count: number, bytes_transferred: number, 
/**
 * Total tokens (input + output + cache) attributed to this provider across
 * all its sessions. Joined from `session_tokens` →
 * `session_token_usage` at read time.
 */
total_tokens: number, 
/**
 * USD cost of this provider's recorded usage. For a pay-per-token
 * (`fireworks`) row this is priced per model from the account's own
 * catalog and is the real spend; for subscription rows it is a blended-rate
 * estimate — a usage-weight signal, not a bill.
 */
est_cost_usd: number, 
/**
 * Per-provider soft limits: a validated JSONB map keyed by
 * canonical window identity (`session` | `weekly_all` | `weekly_model:<id>`),
 * each value `{cap_pct?, bypass_minutes?, pace_cap?}`. NULL ⇒ no soft limits configured.
 */
soft_limits: { [key in string]: SoftLimitConfig } | null, 
/**
 * Usage ticker `{ enabled, step_pct }`; NULL ⇒ off.
 */
usage_notices: UsageNotices | null, 
/**
 * Whether this credential's gauge shows in the header strip.
 */
header_pin: boolean, 
/**
 * Credential health: `true` once the gateway saw the upstream
 * provider reject this credential, cleared on the next successful upstream
 * call. The accounts UI shows a "reauthenticate" badge.
 */
needs_reauth: boolean, last_auth_error: string | null, last_auth_error_at: string | null, 
/**
 * Validated, allowlisted subset of harness settings applied to sessions run
 * under this provider. Config, not secret → returned normally.
 */
settings_json: Record<string, unknown> | null, 
/**
 * Gateway request-shaping settings for this credential (fireworks:
 * `context_length_exceeded_behavior`, session affinity, extra body keys).
 * Distinct from `settings_json`, which is harness settings.
 */
provider_settings: Record<string, unknown> | null, 
/**
 * Per-(account, provider) gateway rate limits `{ rpm?, tpm? }`, enforced in
 * the proxy path. NULL ⇒ no throttling.
 */
rate_limits: RateLimits | null, };
