// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPoolMember } from "./AccountPoolMember";

/**
 * A pool with its membership — what the accounts screen renders.
 */
export type AccountPoolView = { members: Array<AccountPoolMember>, id: string, user_id: string, name: string, 
/**
 * `headroom` (most allocation left wins) or `ordered` (first member with
 * room, by `position`).
 */
strategy: string, 
/**
 * Whether a live session bound to this pool may be moved between members
 * when its account is refused.
 */
failover: boolean, created_at: string, };
