// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One live redirect rule. Exactly one of `to_account` / `to_model` is set
 * (enforced by `account_redirects_one_target`): a rule either moves new
 * sessions to another account or flips the model they spawn with — never both.
 */
export type AccountRedirect = { id: string, user_id: string, from_account: string, to_account: string | null, family: string, match_model: string | null, to_model: string | null, expires_at: string | null, reason: string | null, created_at: string, };
