// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API view of one live share grant on an account. Safe to return —
 * no secrets; just who the account is shared with and since when.
 */
export type AccountShareInfo = { account_id: string, user_id: string, 
/**
 * The grantee's login (`users.name`), joined for display.
 */
user_name: string, action: string, granted_at: string, };
