// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A member as the API renders it: enough for the UI to explain why an account
 * is or is not currently electable, without a second round trip.
 */
export type AccountPoolMember = { account_id: string, name: string, position: number, 
/**
 * False when the member belongs to someone else (shared with the pool's
 * owner). Such a member can leave the pool without warning: the owner may
 * revoke the share or clear `pool_eligible`.
 */
owned: boolean, 
/**
 * The owner's veto. A shared member with this false is kept in the row
 * (so the UI can say why it stopped counting) but never elected.
 */
pool_eligible: boolean, };
