// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable model on a compatible-endpoint or `fireworks` provider:
 * `model` is the `--model` code, `label` the display name. Safe to return over
 * the API — model names are not secret (unlike the credential).
 *
 * Pricing is per *million* tokens in USD and is account-owned data: it is what
 * a pay-per-token provider is metered against, so it lives on the row rather
 * than in a table someone has to redeploy to correct.
 */
export type AccountModel = { model: string, label: string, price_input_per_mtok?: number | null, price_cached_input_per_mtok?: number | null, price_output_per_mtok?: number | null, context_length?: number | null, };
