// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitResetEntry } from "./LimitResetEntry";
import type { LimitResetStatus } from "./LimitResetStatus";
import type { ProviderStatus } from "./ProviderStatus";
import type { UsageWindowView } from "./UsageWindowView";

/**
 * Usage windows surfaced per provider credential. `usage` mirrors
 * Anthropic's free OAuth usage payload (`five_hour`/`seven_day` utilization +
 * reset timestamps); `None` means the provider has no usage API (Codex) or the
 * credential has no active windows — the webui hides the indicator in that
 * case. `account_id` is the provider-row id (the legacy field name is the
 * API contract).
 */
export type AccountUsage = { account_id: string, provider: string, 
/**
 * Raw upstream usage JSON (passed through verbatim) or `null`.
 */
usage: Record<string, { utilization?: number | null, resets_at?: string | null } | null> | null, 
/**
 * Normalized, provider-agnostic usage windows: the collection the
 * UI renders and the soft-limit evaluator gates on. Empty ⇒ no supported
 * windows in the latest response (distinct from a fetch error).
 */
windows: Array<UsageWindowView>, 
/**
 * Seconds since this usage was fetched upstream (0 = just now). Lets the UI
 * show staleness; values refresh on the slow cache TTL, not per request.
 */
age_secs: number, 
/**
 * Whether a usage-limit reset can be claimed right now (Codex reset
 * credits, Claude `juniper_tide`); `None` when the payload has no such block.
 */
limit_reset: LimitResetStatus | null, 
/**
 * Every reset this credential currently offers, usable first then by
 * soonest expiry. Empty ⇒ nothing to claim and nothing to list.
 */
limit_resets: Array<LimitResetEntry>, 
/**
 * The upstream family's incident reading, present only when this
 * credential's provider is degraded: a healthy or unknown upstream is not
 * news, and a compatible endpoint never inherits a first-party incident.
 */
provider_status?: ProviderStatus, };
