// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LimitResetStatus } from "./LimitResetStatus";
import type { UsageWindowView } from "./UsageWindowView";

/**
 * One row of `GET /api/v1/accounts/usage`: a provider credential's usage plus
 * the account it hangs off, so a caller can group without a second request.
 */
export type AccountUsageEntry = { account: string, account_name: string, 
/**
 * The account's identity glyph, so the header can group without a second request.
 */
account_emoji: string | null, 
/**
 * Whether this credential's gauge shows in the header strip.
 */
header_pin: boolean, account_id: string, provider: string, 
/**
 * Raw upstream usage JSON (passed through verbatim) or `null`.
 */
usage: Record<string, { utilization?: number | null, resets_at?: string | null } | null> | null, 
/**
 * Normalized, provider-agnostic usage windows: the collection the
 * UI renders and the soft-limit evaluator gates on. Empty ⇒ no supported
 * windows in the latest response (distinct from a fetch error).
 */
windows: Array<UsageWindowView>, 
/**
 * Seconds since this usage was fetched upstream (0 = just now). Lets the UI
 * show staleness; values refresh on the slow cache TTL, not per request.
 */
age_secs: number, 
/**
 * Whether a usage-limit reset can be claimed right now (Codex reset
 * credits, Claude `juniper_tide`); `None` when the payload has no such block.
 */
limit_reset: LimitResetStatus | null, };
