// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrafficError } from "./TrafficError";
import type { TrafficFrame } from "./TrafficFrame";
import type { TrafficStderrLine } from "./TrafficStderrLine";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * ACP-adapter section: one agent process spoken to over stdio JSON-RPC.
 */
export type AcpDiagnose = { 
/**
 * The agent row (adapter id) this session runs under.
 */
agent: string, 
/**
 * `agentInfo.name` from `initialize`.
 */
agent_name?: string | null, 
/**
 * `agentInfo.version` from `initialize`.
 */
agent_version?: string | null, protocol_version?: number | null, agent_pid?: number | null, 
/**
 * Whether a live command channel exists for this session.
 */
live: boolean, 
/**
 * The agent's own session id.
 */
acp_session_id?: string | null, 
/**
 * `working` (a turn is in flight), `idle` or `unknown`.
 */
turn_status: string, 
/**
 * The agent-side mode id currently applied.
 */
current_mode?: string | null, available_modes?: Array<string>, model?: string | null, 
/**
 * Permission prompts awaiting an answer.
 */
pending_permissions?: Array<string>, 
/**
 * The last `usage_update` cost the agent priced, in USD.
 */
last_cost_usd?: number | null, 
/**
 * The raw `initialize` response: capabilities and auth methods.
 */
initialize?: JsonValue, protocol_errors?: Array<TrafficError>, 
/**
 * Trailing agent stderr lines, oldest first.
 */
stderr_tail?: Array<TrafficStderrLine>, 
/**
 * The last JSON-RPC frames on the agent's stdio, oldest first.
 */
rpc_tail?: Array<TrafficFrame>, };
