// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Adapter implementation id, e.g. `claude-code`, `codex`.
 */
export type AdapterId = string;
