// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identifier for an adapter implementation (e.g. `"claude-code"`,
 * `"codex"`).
 *
 * Adapters compiled into the daemon return their id from `Adapter::id()`;
 * the server uses this string in `sessions.adapter_id` and
 * `adapters_enabled.adapter_id`.
 */
export type AdapterId = string;
