// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserActionKind } from "./UserActionKind";

/**
 * Body for `POST /api/v1/daemon/sessions/{id}/user-actions`.
 */
export type AddUserActionRequest = { title: string, detail?: string | null, kind: UserActionKind, blocking: boolean, };
