// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSource } from "./PluginSource";

export type AdminPluginInfo = { id: string, name: string, description: string, version: string, source: PluginSource, 
/**
 * The instance-wide toggle; directory plugins are always on.
 */
enabled: boolean, };
