// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceSetting } from "./PluginInstanceSetting";
import type { PluginSource } from "./PluginSource";

export type AdminPluginInfo = { id: string, name: string, description: string, version: string, source: PluginSource, 
/**
 * The instance-wide toggle; directory plugins are always on.
 */
enabled: boolean, 
/**
 * Declarations for the admin settings form.
 */
instance_settings: Array<PluginInstanceSetting>, 
/**
 * The plugin declares a backend, so it needs an upstream and a secret.
 */
backend: boolean, 
/**
 * Set by an install that minted a fresh proxy secret; the only response
 * that ever carries it.
 */
proxy_secret?: string, };
