// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type AgentEvent = { "type": "text", content: string, meta: boolean, ts: number, } | { "type": "tool_call", tool: string, input: JsonValue, ts: number, } | { "type": "tool_result", tool: string, output_summary: string, ts: number, } | { "type": "heartbeat", tokens_in: number, tokens_out: number, cost_usd: number, ts: number, } | { "type": "reply", content: string, ts: number, } | { "type": "context_reset", ts: number, } | { "type": "turn_end", ts: number, };
