// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

export type AgentEvent = { "type": "text", content: string, meta: boolean, 
/**
 * `thinking` | `redacted_thinking` | `attachment` | `system_marker` |
 * `turn_annotation` | `queue_op`. `None` is visible prose.
 */
kind?: string | null, 
/**
 * For `queue_op`: `queued` | `dequeued` | `removed` | `cleared`.
 */
operation?: string | null, ts: number, message_id?: string | null, usage?: TokenUsage | null, seq?: number | null, 
/**
 * `None` for assistant text and turns cctui did not originate.
 */
turn_id?: string | null, } | { "type": "tool_call", tool: string, input: JsonValue, 
/**
 * `server_tool_use` for provider-executed tools.
 */
kind?: string | null, ts: number, seq?: number | null, } | { "type": "tool_result", tool: string, output_summary: string, 
/**
 * `server_tool_result` for provider-executed tools.
 */
kind?: string | null, error: boolean, ts: number, seq?: number | null, } | { "type": "heartbeat", tokens_in: number, tokens_out: number, cost_usd: number, ts: number, seq?: number | null, } | { "type": "reply", content: string, ts: number, seq?: number | null, turn_id?: string | null, } | { "type": "context_reset", ts: number, seq?: number | null, } | { "type": "compact_summary", content: string, ts: number, seq?: number | null, } | { "type": "turn_summary", detail: string, status_category?: string | null, needs_action: boolean, ts: number, seq?: number | null, } | { "type": "turn_end", ts: number, seq?: number | null, };
