// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a [`DiffSelection`] could not be resolved to a [`CommentAnchor`]. The
 * webui surfaces these so a reviewer knows a draft is un-anchorable rather than
 * silently publishing it onto the wrong line.
 */
export type AnchorError = { "kind": "stale_head_sha", 
/**
 * The SHA the selection was made against.
 */
selection_sha: string, 
/**
 * The SHA the diff is now at.
 */
diff_sha: string, } | { "kind": "file_not_found" } | { "kind": "line_not_in_diff" } | { "kind": "invalid_range" };
