// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnchorError = { "kind": "stale_head_sha", selection_sha: string, diff_sha: string, } | { "kind": "file_not_found" } | { "kind": "line_not_in_diff" } | { "kind": "invalid_range" };
