// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKeyRow = { id: string, label: string | null, key_preview: string | null, kind: string, created_at: string, expires_at: string | null, revoked_at: string | null, last_used_at: string | null, 
/**
 * The key's granted scopes (`key_acls`), filled by the handler.
 */
scopes: Array<string>, };
