// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiMethod } from "./ApiMethod";

/**
 * One `/api/v1` endpoint.
 */
export type ApiRoute = { 
/**
 * Stable identifier, `{method}_{path}` slugged. What a client names.
 */
id: string, method: ApiMethod, 
/**
 * Path template under [`API_PREFIX`], with `{param}` placeholders.
 */
path: string, summary: string, 
/**
 * Exported TS name of the JSON request body, when the route reads one.
 */
request: string | null, 
/**
 * Exported TS name of the JSON response body.
 */
response: string | null, };
