// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persistent-attach keep-alive status (487) for the session's worker.
 */
export type AttachStatus = { 
/**
 * `held` (attached, socket open), `reconnecting` (backoff between
 * attempts), or `connecting` (task exists, no cycle finished yet).
 */
phase: string, 
/**
 * Current reconnect backoff in ms, when `phase == "reconnecting"`.
 */
backoff_ms?: number | null, 
/**
 * Outcome of the last liveness probe (`has`): `Some(true)` alive,
 * `Some(false)` found dead, `None` no probe yet.
 */
last_probe_alive?: boolean | null, 
/**
 * When the last liveness probe ran (unix ms).
 */
last_probe_at_ms?: number | null, };
