// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/v1/sessions/{id}/labels` — attach an existing label.
 */
export type AttachLabelRequest = { label_id: string, };
