// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a session wants the user's eyes, surfaced as a glyph.
 *
 * Derived from the classifier; today only the "blocked" bucket is
 * surfaced (the ✋ "needs input" hand).
 */
export type Attention = "needs_input";
