// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a tracked PR needs from the viewer. Exactly one per PR; variants are
 * in inbox display order.
 */
export type AttentionBucket = "needs_my_review" | "my_pr_changes_requested" | "my_pr_ci_red" | "my_pr_mergeable" | "waiting";
