// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What attention a tracked PR needs from the viewer, mirroring the session
 * classifier's bucket vocabulary (docs/github-integration.md §6.1).
 *
 * Serialized `snake_case` so the webui inbox groups on the on-wire token. A
 * PR lands in exactly one bucket; the derivation (in `cctui-github`) picks the
 * single most-actionable one. The order here is the natural priority the inbox
 * renders top-to-bottom.
 */
export type AttentionBucket = "needs_my_review" | "my_pr_changes_requested" | "my_pr_ci_red" | "my_pr_mergeable" | "waiting";
