// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/v1/sessions/{id}/auto-approve` — toggle the cctui-side
 * auto-approve convenience.
 */
export type AutoApproveRequest = { enabled: boolean, };
