// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Bookmark = { id: string, 
/**
 * Source session, or `None` once that session has been deleted.
 */
session_id: string | null, 
/**
 * Position of the message within the source transcript.
 */
seq: number | null, message_id: string | null, title: string, 
/**
 * The snapshotted message text, as Markdown.
 */
body: string, role: string, 
/**
 * Denormalised at save time so a dead-link bookmark still says where it
 * came from.
 */
session_name: string | null, note: string | null, message_ts: string, created_at: string, };
