// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User/assistant transcript as markdown, oldest turns elided past the caps.
 */
export type BriefResponse = { markdown: string, turns: number, omitted: number, truncated: boolean, };
