// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The four session buckets clients group on. Serialized `snake_case`
 * (`working` / `blocked` / `review` / `done`) and shared verbatim by the
 * TUI and web UI as the on-wire grouping signal.
 */
export type Bucket = "working" | "blocked" | "review" | "done";
