// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCapability } from "./GithubCapability";

/**
 * The capability envelope. One field per optional integration; the webui reads
 * `github.available` to mount the lazy `/github` route + nav, and
 * `github.enabled` to decide between the inbox and the first-run setup state.
 *
 * CCT-399: `claude_litellm_models` was dropped — self-hosted models are now a
 * per-account property surfaced by `GET /accounts`, not a server-global list.
 */
export type CapabilitiesResponse = { github: GithubCapability, };
