// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCapability } from "./GithubCapability";

/**
 * The capability envelope. One field per optional integration; the webui reads
 * `github.enabled` to decide whether to mount the lazy `/github` route + nav.
 */
export type CapabilitiesResponse = { github: GithubCapability, };
