// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCapability } from "./GithubCapability";
import type { LiteLlmModelInfo } from "./LiteLlmModelInfo";

/**
 * The capability envelope. One field per optional integration; the webui reads
 * `github.available` to mount the lazy `/github` route + nav, and
 * `github.enabled` to decide between the inbox and the first-run setup state.
 */
export type CapabilitiesResponse = { github: GithubCapability, 
/**
 * Operator-declared self-hosted Claude models (empty unless configured).
 */
claude_litellm_models: Array<LiteLlmModelInfo>, };
