// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A catalog entry as the admin UI sees it: the published metadata plus what
 * this instance has installed.
 */
export type CatalogPluginInfo = { id: string, name: string, description: string, version: string, homepage: string | null, 
/**
 * `None` until this instance installs it.
 */
installed_version: string | null, 
/**
 * The catalog version differs from the installed one.
 */
update_available: boolean, };
