// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CctuiverseInbound } from "./CctuiverseInbound";
import type { CctuiverseOutbound } from "./CctuiverseOutbound";

/**
 * The owner's choices for one link. Every field defaults, so a partial or
 * empty stored object reads back whole.
 */
export type CctuiverseSettings = { inbound: CctuiverseInbound, outbound: CctuiverseOutbound, review_outbound: boolean, share_transcript: boolean, expires_at: string | null, max_messages: number | null, };
