// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A held inbound or review-pending outbound message.
 */
export type CctuiverseMessageView = { id: number, message_id: string, direction: string, kind: string, text: string, status: string, created_at: string, };
