// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happens to a message the peer sends.
 */
export type CctuiverseInbound = "deliver" | "hold";
