// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CctuiverseLinkKind } from "./CctuiverseLinkKind";
import type { CctuiverseLinkRole } from "./CctuiverseLinkRole";
import type { CctuiverseLinkState } from "./CctuiverseLinkState";
import type { CctuiverseSettings } from "./CctuiverseSettings";

export type CctuiverseLinkView = { id: string, session_id: string | null, room_id: string | null, kind: CctuiverseLinkKind, role: CctuiverseLinkRole, state: CctuiverseLinkState, label: string, peer_label: string | null, 
/**
 * Host name of the peer's server only.
 */
peer_host: string | null, peer_room_name: string | null, 
/**
 * `xxxx-xxxx-xxxx-xxxx`, derived from both public keys; `None` until active.
 */
safety_code: string | null, settings: CctuiverseSettings, sent_count: number, held_count: number, review_count: number, invite_expires_at: string | null, created_at: string, activated_at: string | null, closed_at: string | null, };
