// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How this side's agent reaches the peer: through `CctuiSend`, by forwarding
 * each turn's final reply, or both.
 */
export type CctuiverseOutbound = "tool" | "auto" | "both";
