// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReleaseNote } from "./ReleaseNote";

export type ChangelogResponse = { version: string, 
/**
 * Releases published since `version`, newest first (capped server-side).
 * Empty when up to date or before the probe's first answer.
 */
releases: Array<ReleaseNote>, };
