// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated CI state for a PR's head SHA — the counts a row badge needs
 * without shipping every individual check.
 */
export type CheckSummary = { 
/**
 * Checks that completed successfully (or neutral/skipped).
 */
passed: number, 
/**
 * Checks that completed with a failing conclusion.
 */
failed: number, 
/**
 * Checks not yet completed (`queued` / `in_progress`).
 */
pending: number, };
