// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed CI check (`check_run` or legacy commit status) for a head SHA.
 */
export type CheckUpsert = { repo: string, head_sha: string, 
/**
 * GitHub's `check_run` id, or `status:<context>` for legacy commit statuses.
 */
external_id: string, name: string, 
/**
 * `queued` | `in_progress` | `completed`.
 */
status: string, 
/**
 * `success` | `failure` | … ; `None` while running.
 */
conclusion: string | null, details_url: string | null, };
