// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed `check_run` or legacy commit status.
 */
export type CheckUpsert = { repo: string, head_sha: string, 
/**
 * `check_run` id, or `status:<context>` for a commit status.
 */
external_id: string, name: string, 
/**
 * `queued` | `in_progress` | `completed`.
 */
status: string, 
/**
 * `None` while running.
 */
conclusion: string | null, details_url: string | null, };
