// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One JSON-RPC protocol error (`<method>: <error>`), secret-redacted.
 */
export type CodexProtocolError = { ts_ms: number, message: string, 
/**
 * Which transport the error was observed on: `stdio` or `shared`.
 */
transport: string, };
