// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A retained `codex app-server` stderr line, secret-redacted.
 */
export type CodexStderrLine = { ts_ms: number, line: string, };
