// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One retained JSON-RPC frame, secret-redacted and truncated to 2 KiB.
 */
export type CodexRpcFrame = { ts_ms: number, 
/**
 * `out` (daemon → app-server) or `in` (app-server → daemon).
 */
direction: string, 
/**
 * The frame's `method`, else its `id`, else `frame`.
 */
label: string, json: string, };
