// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Codex-adapter-specific diagnostics.
 *
 * Present only when the session is driven by the codex adapter; `None` for
 * claude-code, whose facts are the neutral top-level fields instead. Kept as
 * One retained `codex app-server` stderr line, secret-redacted.
 */
export type CodexStderrLine = { ts_ms: number, line: string, };
