// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Codex-adapter-specific diagnostics (CCT-640).
 *
 * Present only when the session is driven by the codex adapter; `None` for
 * claude-code, whose facts are the neutral top-level fields instead. Kept as
 * an optional tagged section so the claude wire shape stays unchanged
 * (additive-only).
 */
export type CodexDiagnose = { 
/**
 * Discovered `codex app-server` version (from the `initialize` userAgent).
 */
codex_version: string | null, 
/**
 * The Codex version cctui is built/tested against (`CODEX_PINNED_VERSION`).
 */
pinned_version: string, 
/**
 * The minimum app-server protocol version still spoken (`CODEX_MIN_VERSION`).
 */
min_version: string, 
/**
 * Whether the discovered version is at or above `min_version`.
 */
version_supported: boolean | null, 
/**
 * Transport to the app-server child (always `stdio` today).
 */
transport: string, 
/**
 * app-server child PID, when a live session owns one.
 */
app_server_pid: number | null, 
/**
 * Whether a live command channel exists for this session.
 */
live: boolean, 
/**
 * Whether the durable session registry holds a resumable record.
 */
registered: boolean, 
/**
 * The active thread id (the codex `local_id`).
 */
thread_id: string | null, 
/**
 * In-flight turn id, when a turn is running.
 */
active_turn_id: string | null, 
/**
 * Turn status: `working` (a turn is in flight) or `idle`.
 */
turn_status: string, 
/**
 * Count of outstanding outbound JSON-RPC requests.
 */
pending_rpc_count: number, 
/**
 * Methods of the outstanding JSON-RPC requests.
 */
pending_rpc_methods: Array<string>, 
/**
 * Last JSON-RPC protocol error seen on this session, if any.
 */
last_protocol_error: string | null, 
/**
 * Rollout (transcript) file path for the thread.
 */
rollout_path: string | null, 
/**
 * Rollout file size in bytes at report time — the tail-offset analogue for
 * an app-server-owned rollout (no external tail consumes it).
 */
rollout_size_bytes: number | null, 
/**
 * Cheap auth/account posture: whether the launch env carries gateway
 * routing credentials.
 */
auth_state: string | null, 
/**
 * Registry↔live mismatch description, when the two disagree abnormally
 * (e.g. a live channel with no durable record).
 */
registry_live_mismatch: string | null, };
