// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

/**
 * A [`DiffSelection`] resolved to GitHub review-comment coordinates.
 */
export type CommentAnchor = { path: string, commit_id: string, 
/**
 * End line of a range.
 */
line: number, side: DiffSide, start_line?: number | null, 
/**
 * Always equals `side` when set.
 */
start_side?: DiffSide | null, };
