// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

/**
 * A fully resolved GitHub review-comment anchor — the precise shape a
 * `POST .../reviews` comment entry needs. Produced by resolving a
 * [`DiffSelection`] against the [`PullDiff`] it targets. Every field maps 1:1
 * to GitHub's review-comment API.
 */
export type CommentAnchor = { 
/**
 * GitHub comment `path` (head-side path).
 */
path: string, 
/**
 * GitHub `commit_id` — the head SHA the comment is anchored to.
 */
commit_id: string, 
/**
 * GitHub `line` — the (1-based) line on `side`. For a multi-line comment
 * this is the END line of the range.
 */
line: number, 
/**
 * GitHub `side` — `LEFT` (base) or `RIGHT` (head).
 */
side: DiffSide, 
/**
 * GitHub `start_line` — the START line of a multi-line range. `None` for a
 * single-line comment.
 */
start_line: number | null, 
/**
 * GitHub `start_side` — the side of `start_line`. Always equals `side`
 * here (cctui never anchors a range across the two columns). `None` when
 * `start_line` is `None`.
 */
start_side: DiffSide | null, };
