// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCredentialKind } from "./GithubCredentialKind";

/**
 * A connector as read back; secrets are never included.
 */
export type ConnectorInfo = { id: string, name: string, credential_kind: GithubCredentialKind, 
/**
 * Masked fragment, e.g. `github_pat_ab…wxyz`.
 */
credential_preview: string, has_webhook_secret: boolean, repos: Array<string>, user_id: string, 
/**
 * ISO-8601.
 */
created_at: string, 
/**
 * ISO-8601. `None` until first polled.
 */
last_polled_at: string | null, 
/**
 * `None` when the last poll succeeded.
 */
last_error: string | null, };
