// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The editable half of an item.
 */
export type ContextItemSpec = { kind: string, name: string, title: string, body: string, scope: string, scope_ref?: string | null, tags: Array<string>, enabled: boolean, };
