// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextItemSpec = { kind: string, name: string, title: string, body?: string, scope?: string, 
/**
 * Machine id, working-dir prefix or label id. `None` for `user` scope.
 */
scope_ref?: string | null, tags?: Array<string>, enabled?: boolean, };
