// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextItem = { id: string, user_id: string, 
/**
 * `memory` or `prompt`.
 */
kind: string, 
/**
 * Slug, unique per `(user_id, kind)`; the stable reference a profile or a
 * spawn request names.
 */
name: string, title: string, body: string, 
/**
 * `user` | `machine` | `path` | `label`.
 */
scope: string, 
/**
 * Machine id, working-dir prefix or label id. `None` for `user` scope.
 */
scope_ref?: string | null, tags: Array<string>, enabled: boolean, version: number, created_at: string, updated_at: string, };
