// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One transcript match inside a single session. `seq` is `stream_events.id`,
 * the same address pins and the client's jump primitive use; `role` is the
 * webui's `MsgCategory`.
 */
export type ConversationHit = { seq: number, ts: number, role: string, tool: string | null, snippet: string, };
