// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationHit } from "./ConversationHit";

/**
 * `total` counts the hits returned; `truncated` says the scan stopped at the
 * cap, so the real total is higher.
 */
export type ConversationSearchResponse = { hits: Array<ConversationHit>, total: number, truncated: boolean, 
/**
 * Tool ids seen among the hits, for the `tool:` autocomplete.
 */
tools: Array<string>, };
