// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateProfileRequest = { name: string, harness: string, account_id?: string | null, model_alias?: string | null, effort?: string | null, permission_mode?: string | null, };
