// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateBookmark = { session_id: string | null, seq: number | null, message_id: string | null, title: string, body: string, role: string, session_name: string | null, note: string | null, 
/**
 * Message timestamp (epoch millis on the wire, as the UI carries it).
 */
message_ts: number, };
