// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCredentialKind } from "./GithubCredentialKind";

/**
 * Request body for `POST /api/v1/github/connectors`.
 *
 * Carries the **plaintext** credential and webhook secret exactly once, on
 * create. The server encrypts both at rest (`crate::crypto` XOR-vault pattern,
 * same key as the OAuth-account vault) and never echoes them back — every read
 * path returns [`ConnectorInfo`] with the credential masked.
 */
export type CreateConnector = { 
/**
 * Human-readable label for this connector (e.g. `personal`, `work`).
 */
name: string, 
/**
 * Whether `credential` is a PAT or an App installation token.
 */
credential_kind: GithubCredentialKind, 
/**
 * The GitHub credential. Stored encrypted; never returned by any endpoint.
 */
credential: string, 
/**
 * `owner/name` slugs (or bare `owner` for whole-org) this connector tracks.
 */
repos: Array<string>, 
/**
 * Optional webhook signing secret (`X-Hub-Signature-256`). Stored
 * encrypted; never returned. A later story verifies signatures with it.
 */
webhook_secret: string | null, 
/**
 * Owning user — required (and only honoured) when authenticated with the
 * admin token, which has no user identity of its own.
 */
user_id: string | null, };
