// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Get-or-create by name.
 */
export type CreateLabelRequest = { name: string, color: string, };
