// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewVerdict } from "./ReviewVerdict";

/**
 * Opens the caller's draft for a PR, or returns the open one.
 */
export type CreateReviewDraft = { 
/**
 * Defaults to `comment`.
 */
verdict: ReviewVerdict | null, };
