// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/v1/labels` — create (or get-or-create by name) a label.
 */
export type CreateLabelRequest = { name: string, color: string, };
