// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GithubCredentialKind } from "./GithubCredentialKind";

/**
 * Body for `POST /api/v1/github/connectors`. The only place the plaintext
 * credential and webhook secret travel; both are stored encrypted.
 */
export type CreateConnector = { name: string, credential_kind: GithubCredentialKind, credential: string, 
/**
 * `owner/name` slugs, or bare `owner` for a whole org.
 */
repos: Array<string>, 
/**
 * `X-Hub-Signature-256` secret.
 */
webhook_secret: string | null, 
/**
 * Required with the admin token, ignored otherwise.
 */
user_id: string | null, };
