// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

export type CreateDraftComment = { path: string, side: DiffSide, 
/**
 * End line of a range.
 */
line: number, start_line?: number | null, body: string, 
/**
 * Parent GitHub comment id.
 */
in_reply_to?: number | null, };
