// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

/**
 * Request body for `POST .../drafts/{draft_id}/comments` — add one inline draft
 * comment anchored on the reviewer's diff selection (GH-VIEW-2 coordinates).
 */
export type CreateDraftComment = { 
/**
 * Head-side file path the comment anchors on.
 */
path: string, 
/**
 * Which side the selected line lives on.
 */
side: DiffSide, 
/**
 * 1-based line on `side` (the END line for a multi-line range).
 */
line: number, 
/**
 * Inclusive start line for a multi-line range; `None` for a single line.
 */
start_line: number | null, 
/**
 * The comment text.
 */
body: string, 
/**
 * When replying to an existing GitHub thread, the parent comment id.
 */
in_reply_to: number | null, };
