// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountModel } from "./AccountModel";
import type { RateLimits } from "./RateLimits";
import type { SoftLimitConfig } from "./SoftLimitConfig";

/**
 * `POST /api/v1/accounts` payload: the identity fields, plus an
 * optionally flattened [`ProviderSpec`] — supplying `provider` creates the
 * account and its first credential in one call (the legacy shape).
 */
export type CreateAccount = { name: string, 
/**
 * Identity glyph; one emoji grapheme. Blank/absent ⇒ the letter square.
 */
emoji?: string, 
/**
 * Owning user — required (and only honoured) when authenticated with the
 * admin token, which has no user identity of its own.
 */
user_id?: string, 
/**
 * Extra environment variables for sessions run under this account.
 * Stored ENCRYPTED at rest and never returned over the API (write-only,
 * like the OAuth tokens). An empty map ⇒ no override.
 */
env_json?: Record<string, string>, 
/**
 * `anthropic` | `openai` (native subscription) | `anthropic-compatible` |
 * `openai-compatible`. Optional only when flattened into
 * [`CreateAccount`] (identity-only create); required on the provider route.
 */
provider?: string, 
/**
 * OAuth refresh token (subscription providers). Optional for compatible
 * endpoints, which store only a static credential (in `access_token`).
 * Stored encrypted; the gateway exchanges it for access tokens on demand.
 */
refresh_token?: string, 
/**
 * Initial access token (subscription) OR the static credential (a compatible
 * endpoint's bearer/api key). Stored encrypted; never read back.
 */
access_token?: string, 
/**
 * Optional access-token expiry (unix seconds). When absent the gateway
 * refreshes on first use (subscription) / never refreshes (compatible).
 */
expires_at?: number, 
/**
 * Compatible-endpoint base URL, e.g. a LiteLLM/vLLM/Ollama-proxy.
 * Required for `*-compatible` providers; ignored for native ones.
 */
base_url?: string, 
/**
 * Models this credential offers; empty falls back to the harness catalog.
 */
models?: Array<AccountModel>, 
/**
 * Logical→concrete model alias map, e.g.
 * `{"opus": "claude-opus-4-8[1m]"}`. Honoured for every provider.
 */
model_aliases?: Record<string, string>, 
/**
 * Credential scheme for a compatible endpoint: `bearer` | `api_key`.
 * Defaults to `bearer`. Native providers are always `oauth`.
 */
auth_scheme?: string, 
/**
 * Per-provider soft limits: a canonical-key map
 * `{ "session": {cap_pct?, bypass_minutes?, pace_cap?}, "weekly_all": {…}, … }`.
 * Absent ⇒ NULL (no caps). Validated before persist.
 */
soft_limits?: { [key in string]: SoftLimitConfig }, 
/**
 * Validated, allowlisted harness settings for this provider.
 * Server rejects MANAGED/SYSTEM keys before persist. Returned normally.
 */
settings_json?: Record<string, unknown>, 
/**
 * Gateway request-shaping settings. Absent on a `fireworks` create seeds
 * the defaults so every knob is visible and editable from the start.
 */
provider_settings?: Record<string, unknown>, 
/**
 * Per-(account, provider) gateway rate limits `{ rpm?, tpm? }`. Absent ⇒
 * NULL (no throttling). Validated before persist.
 */
rate_limits?: RateLimits, };
