// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatePoolRequest = { name: string, 
/**
 * `headroom` (default) or `ordered`.
 */
strategy?: string, 
/**
 * Whether a live session may be moved between members. Defaults to false:
 * creating a pool changes how launches pick, nothing about running work.
 */
failover?: boolean, 
/**
 * Members, in election order for the `ordered` strategy.
 */
accounts?: string[], 
/**
 * The admin token has no user identity and must name the pool's owner.
 */
user_id?: string | null, };
