// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewVerdict } from "./ReviewVerdict";

/**
 * Request body for `POST /api/v1/github/pulls/{connector_id}/{owner}/{name}/{number}/drafts`
 * — open (or reuse) the caller's draft for a PR.
 *
 * The verdict defaults to `comment`; a user reusing their open draft keeps the
 * existing row (one open draft per user+pull). The PR ref is taken from the path.
 */
export type CreateReviewDraft = { 
/**
 * The pending verdict; defaults to `comment` when omitted.
 */
verdict: ReviewVerdict | null, };
