// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyCacheLoss = { 
/**
 * Local calendar day, `YYYY-MM-DD`.
 */
day: string, ttl_expired: number, gateway_rewrote_body: number, unknown: number, total: number, busts: number, };
