// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One component the provider reports as anything but operational.
 */
export type DegradedComponent = { name: string, 
/**
 * Statuspage component status (`degraded_performance`, `major_outage`, …).
 */
status: string, };
