// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceAuthStart = { 
/**
 * The polling secret. Never displayed; the user types `user_code` instead.
 */
device_code: string, 
/**
 * The short code the user reads out to the browser, `XXXX-XXXX`.
 */
user_code: string, verification_uri: string, 
/**
 * `verification_uri` with the code pre-filled, for a clickable terminal.
 */
verification_uri_complete: string, expires_in_secs: number, 
/**
 * Minimum seconds between polls. Polling faster earns a 429.
 */
interval_secs: number, };
