// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { DeviceAuthStatus } from "./DeviceAuthStatus";

export type DeviceAuthRequestInfo = { user_code: string, client_name: string | null, expires_in_secs: number, status: DeviceAuthStatus, };
