// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceAuthStartRequest = { 
/**
 * What to show the approving user, e.g. `cctui on thinkpad`.
 */
client_name: string | null, };
