// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceAuthStatus } from "./DeviceAuthStatus";

export type DeviceAuthPoll = { status: DeviceAuthStatus, 
/**
 * The minted key, present exactly once: on the first poll after approval.
 */
token: string | null, };
