// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One dated fact in a [`SessionDiagnose`] report.
 *
 * `value: None` + `missing_reason` means the daemon could not produce the
 * fact right now; the call as a whole still succeeds.
 */
export type DiagnoseFact<T> = { value?: T | null, 
/**
 * Unix ms. `None` when the signal carries no timestamp.
 */
observed_at_ms?: number | null, 
/**
 * `generated_at_ms - observed_at_ms`, clamped to `>= 0`.
 */
age_ms?: number | null, 
/**
 * Producing subsystem, e.g. `hook`, `control_socket`, `discovery`.
 */
source: string, 
/**
 * Why `value` is absent. Always `Some` when `value` is `None`.
 */
missing_reason?: string | null, };
