// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One dated fact in a [`SessionDiagnose`] report.
 *
 * `value: None` + `missing_reason` means the daemon could not produce the
 * fact right now; the call as a whole still succeeds.
 */
export type DiagnoseFact<T> = { value?: T | null, 
/**
 * Unix epoch millis when the daemon last observed this fact. `None`
 * when the underlying signal carries no timestamp.
 */
observed_at_ms?: number | null, 
/**
 * Staleness at report-build time: `generated_at_ms - observed_at_ms`,
 * clamped to `>= 0`.
 */
age_ms?: number | null, 
/**
 * Which input/subsystem produced the fact (e.g. `hook`,
 * `control_socket`, `discovery`, `filesystem`).
 */
source: string, 
/**
 * Why `value` is absent. Always `Some` when `value` is `None`.
 */
missing_reason?: string | null, };
