// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The role of a [`DiffLine`] within its hunk.
 */
export type DiffLineKind = "context" | "add" | "del";
