// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of the diff a selected line lives on, in cctui's own vocabulary
 * (a rendered split/unified view has an old column and a new column). Maps to
 * GitHub's `LEFT` (base/old) and `RIGHT` (head/new) review-comment sides.
 */
export type DiffSide = "old" | "new";
