// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

export type DiffHunk = { 
/**
 * 1-based.
 */
old_start: number, old_lines: number, 
/**
 * 1-based.
 */
new_start: number, new_lines: number, 
/**
 * Text after the second `@@`.
 */
header?: string | null, lines: Array<DiffLine>, };
