// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

/**
 * A reviewer's selection in the rendered diff, before it is resolved to a
 * GitHub anchor.
 *
 * This is what the draft UI (GH-VIEW-4) persists per comment:
 * the file path, the side, and the (display) line — optionally a multi-line
 * range whose `start_line..=line` is inclusive. `head_sha` records the SHA the
 * selection was made against, so a later force-push (head SHA rotated) can
 * invalidate stale anchors (docs §11).
 */
export type DiffSelection = { 
/**
 * The file's head-side path (the current path; for a rename this is the new
 * name — GitHub anchors comments on the new path).
 */
path: string, 
/**
 * Which side the selected line is on.
 */
side: DiffSide, 
/**
 * 1-based line number on the selected side (old-side number when `side` is
 * `Old`, new-side number when `New`).
 */
line: number, 
/**
 * For a multi-line selection, the (inclusive) start line on the same side.
 * `None` for a single-line comment. Must be `<= line` and on the same side.
 */
start_line: number | null, 
/**
 * The head SHA the selection was made against. A diff whose `head_sha`
 * differs (force-push) makes this selection stale — see [`anchor`] resolve.
 */
head_sha: string, };
