// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

/**
 * One changed file in a PR diff: its path(s), change status, and parsed hunks.
 */
export type DiffFile = { 
/**
 * Current path (head side). For a delete this is the removed path.
 */
path: string, 
/**
 * Previous path when the file was renamed/moved; `None` otherwise.
 */
previous_path?: string | null, 
/**
 * GitHub's `status`: `added` | `modified` | `removed` | `renamed` |
 * `copied` | `changed` | `unchanged`.
 */
status: string, additions: number, deletions: number, 
/**
 * Parsed hunks. Empty for a binary file or a file whose patch could not be
 * fetched even via the blob fallback (`truncated` is then `true`).
 */
hunks: Array<DiffHunk>, 
/**
 * GitHub flagged the inline patch as omitted (too large) **and** the blob
 * fallback did not (or could not) reconstruct it — the webui shows a
 * "load full file" affordance rather than a misleading empty diff.
 */
truncated: boolean, 
/**
 * A binary file has no textual patch; the webui renders a binary badge.
 */
binary: boolean, 
/**
 * The file's blob SHA on the head side (GitHub's `sha`), for blob-keyed
 * "reviewed" marks (GH-VIEW-6) and the blob fallback.
 */
blob_sha?: string | null, };
