// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

export type DiffFile = { 
/**
 * Head-side path; the removed path for a delete.
 */
path: string, 
/**
 * Set for renames.
 */
previous_path?: string | null, 
/**
 * `added` | `modified` | `removed` | `renamed` | `copied` | `changed` | `unchanged`.
 */
status: string, additions: number, deletions: number, 
/**
 * Empty for binaries and for `truncated` files.
 */
hunks: Array<DiffHunk>, 
/**
 * GitHub omitted the patch and the blob fallback could not rebuild it.
 */
truncated: boolean, binary: boolean, 
/**
 * Head-side blob SHA; keys "reviewed" marks.
 */
blob_sha?: string | null, };
