// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

/**
 * A reviewer's diff selection. A different diff `head_sha` makes it stale.
 */
export type DiffSelection = { 
/**
 * Head-side path.
 */
path: string, side: DiffSide, 
/**
 * 1-based, on `side`.
 */
line: number, 
/**
 * Inclusive range start on the same side, `<= line`.
 */
start_line?: number | null, head_sha: string, };
