// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";

export type DiffLine = { kind: DiffLineKind, 
/**
 * Without the leading ` `/`+`/`-` marker.
 */
content: string, 
/**
 * 1-based. `None` for an added line.
 */
old_line?: number | null, 
/**
 * 1-based. `None` for a deleted line.
 */
new_line?: number | null, };
