// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

/**
 * One hunk (`@@ -a,b +c,d @@`) of a file's diff.
 */
export type DiffHunk = { 
/**
 * 1-based starting line on the old (base) side.
 */
old_start: number, 
/**
 * Number of old-side lines the hunk covers.
 */
old_lines: number, 
/**
 * 1-based starting line on the new (head) side.
 */
new_start: number, 
/**
 * Number of new-side lines the hunk covers.
 */
new_lines: number, 
/**
 * The hunk's section heading (the text after the second `@@`), when present.
 */
header?: string | null, lines: Array<DiffLine>, };
