// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";

/**
 * One line within a diff hunk.
 */
export type DiffLine = { 
/**
 * `context` (unchanged) | `add` | `del`.
 */
kind: DiffLineKind, 
/**
 * Line text **without** the leading ` `/`+`/`-` marker.
 */
content: string, 
/**
 * 1-based line number on the old (base) side; `None` for an added line.
 */
old_line?: number | null, 
/**
 * 1-based line number on the new (head) side; `None` for a deleted line.
 */
new_line?: number | null, };
