// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DispatchAccount } from "./DispatchAccount";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Dispatcher-routed session start. `payload` is opaque and forwarded verbatim.
 */
export type DispatchRequest = { dispatcher: string, 
/**
 * Idempotency key; minted when absent.
 */
session_id?: string | null, 
/**
 * Minutes. `None` = runtime default.
 */
timeout?: number | null, 
/**
 * Bearer capability the worker posts its result to. Never logged or persisted.
 */
reply_url?: string | null, 
/**
 * The server posts the completion payload here on any terminal state, crashes included.
 */
notify_url?: string | null, 
/**
 * Signs the webhook body: `X-CCTUI-Signature: sha256=<hex>`. Never logged.
 */
notify_secret?: string | null, payload?: JsonValue, 
/**
 * Account whose gateway env is merged into `payload.env`.
 */
account?: string | null, 
/**
 * `None` = anthropic.
 */
provider?: string | null, 
/**
 * At most one per provider family. Takes precedence over `account`.
 */
accounts?: Array<DispatchAccount>, };
