// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `(account, provider)` entry in [`DispatchRequest::accounts`].
 */
export type DispatchAccount = { 
/**
 * Named account to mint a gateway token for.
 */
account: string, 
/**
 * Provider disambiguating a name shared across providers. `None` → the
 * anthropic family, matching the singular-account default.
 */
provider: string | null, };
