// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DispatchResponse = { session_id: string, dispatcher: string, 
/**
 * Opaque dispatcher handle.
 */
handle: string, namespace?: string | null, 
/**
 * `dispatched`, `deduplicated` or `redispatched`.
 */
status: string, };
