// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * CCT-107: dispatcher-routed session start.
 *
 * `dispatcher` selects which [`Dispatcher`] impl on the server materializes
 * the request (e.g. `"k8s_job"`). Everything else is deliberately
 * runtime-agnostic: cctui mints/dedups the session, carries `reply_url` to
 * the runtime, sets the per-flow `timeout`, and forwards `payload` verbatim.
 *
 * `payload` is **opaque to cctui** — never typed or inspected here. It is
 * forwarded verbatim to the dispatcher, so the caller↔runtime contract can
 * evolve with zero cctui changes.
 */
export type DispatchRequest = { dispatcher: string, 
/**
 * Optional pre-minted session id. When absent the server mints one.
 * Doubles as the **idempotency key**: a repeat dispatch with the same
 * id returns the existing session without launching a second runtime.
 */
session_id: string | null, 
/**
 * Per-flow timeout in minutes. Sets the K8s Job `activeDeadlineSeconds`
 * and is mirrored by the caller's own wait limit. Falls back to the
 * runtime default when absent.
 */
timeout: number | null, 
/**
 * Caller resume URL (e.g. an automation `$execution.resumeUrl`). A **bearer
 * capability** — carried to the runtime, never logged or persisted.
 * The worker POSTs its deterministic result here (CCT-119).
 */
reply_url: string | null, 
/**
 * Free-form, opaque to cctui. Forwarded to the runtime as-is.
 */
payload: JsonValue, };
