// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DispatchResponse = { session_id: string, dispatcher: string, 
/**
 * Opaque per-dispatcher identifier (e.g. `"jobs/claude-worker-abc-…"`).
 */
handle: string, namespace: string | null, status: string, };
