// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dispatched-pod turn-complete watcher state.
 */
export type DispatchStatus = { seen_busy: boolean, done: boolean, marker_path: string, };
