// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `(account, provider)` entry in [`DispatchRequest::accounts`].
 */
export type DispatchAccount = { account: string, 
/**
 * `None` = anthropic.
 */
provider?: string | null, };
