// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndReasonInfo } from "./EndReasonInfo";
import type { PermissionMode } from "./PermissionMode";
import type { ProviderInfo } from "./ProviderInfo";
import type { UsageProbeInfo } from "./UsageProbeInfo";

/**
 * Body of `GET /api/v1/meta/domain`.
 */
export type DomainMeta = { providers: Array<ProviderInfo>, usage_probes: Array<UsageProbeInfo>, end_reasons: Array<EndReasonInfo>, permission_modes: Array<PermissionMode>, };
