// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Draft } from "./Draft";

/**
 * `GET /api/v1/drafts` — every draft the caller owns, newest first. The TUI
 * pulls this once at startup instead of a request per session.
 */
export type DraftList = { drafts: Array<Draft>, };
