// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSide } from "./DiffSide";

export type DraftCommentInfo = { id: string, draft_id: string, path: string, side: DiffSide, line: number, start_line?: number | null, body: string, 
/**
 * `None` until published.
 */
github_comment_id?: number | null, in_reply_to?: number | null, created_at: string, updated_at: string, };
