// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who authored a review draft: a human reviewer or a review agent session.
 */
export type DraftAuthorKind = "user" | "agent";
