// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a draft is still local/editable or has been published to GitHub.
 */
export type DraftStatus = "draft" | "published";
