// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The arbitration output: the session's effective state and the raw signals
 * it was derived from. The wrapping fact's `source` says which input won
 * (`hook` / `activity` / `timeout`).
 */
export type EffectiveState = { 
/**
 * Human-readable verdict, e.g. `awaiting ask answer`,
 * `blocked: approve Bash: …`, `active/working`, `hibernated`, `dead`.
 */
verdict: string, tempo?: string | null, state?: string | null, detail?: string | null, activity?: string | null, };
