// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndTone } from "./EndTone";
import type { SessionEndReason } from "./SessionEndReason";

/**
 * One row of the end-reason table served to clients, so neither of them
 * hardcodes the tone rules.
 */
export type EndReasonInfo = { reason: SessionEndReason, tone: EndTone, muted: boolean, failed_start: boolean, };
