// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Colour tier for an end badge.
 */
export type EndTone = "neutral" | "ok" | "warn" | "danger" | "info";
