// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Control shape for a curated env var in the account-settings editor.
 */
export type EnvKind = "flag" | "number" | "string" | "enum";
