// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Policy } from "./Policy";

/**
 * A curated environment variable exposed as an account default.
 */
export type EnvVar = { 
/**
 * Variable name (e.g. `"ANTHROPIC_MODEL"`).
 */
name: string, 
/**
 * Grouping for the editor UI (`model`/`context`/`thinking`/`tokens`/`skills`/
 * `timeouts`/`telemetry`).
 */
group: string, 
/**
 * Exposure policy tag.
 */
tag: Policy, 
/**
 * Human-readable notes.
 */
notes: string | null, };
