// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvKind } from "./EnvKind";
import type { Policy } from "./Policy";

/**
 * A curated environment variable exposed as an account default.
 */
export type EnvVar = { 
/**
 * Variable name (e.g. `"ANTHROPIC_MODEL"`).
 */
name: string, 
/**
 * Grouping for the editor UI (`model`/`context`/`thinking`/`tokens`/`skills`/
 * `timeouts`/`telemetry`).
 */
group: string, 
/**
 * Exposure policy tag.
 */
tag: Policy, 
/**
 * Control shape rendered by the editor (CCT-591).
 */
kind: EnvKind, 
/**
 * Allowed values for an `enum`-kind var (e.g. effort levels).
 */
values: Array<string> | null, 
/**
 * settings.json key this env var aliases (CCT-591), when one exists — the
 * editor merges the two into ONE row that reads/writes the settings key.
 */
settings_equiv: string | null, 
/**
 * Another env var this is an exact alias of (`DO_NOT_TRACK` == `DISABLE_TELEMETRY`).
 * The editor folds aliases into the primary's row so only one renders.
 */
env_alias_of: string | null, 
/**
 * Human-readable row label (like curated settings keys have).
 */
label: string | null, 
/**
 * Human-readable notes.
 */
notes: string | null, };
