// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One recorded lifecycle transition.
 *
 * `summary` is rendered at insert time and `detail` keeps the denormalised
 * `session_name` / `machine_label`, so a row stays readable once its subject
 * is gone and the id columns are null.
 */
export type EventRecord = { id: number, occurred_at: string, 
/**
 * `<subject>.<verb>`, e.g. `session.ended`; clients render unknown kinds generically.
 */
kind: string, 
/**
 * `info` | `warn` | `error`.
 */
severity: string, session_id: string | null, machine_id: string | null, user_id: string | null, 
/**
 * `user:<id>` | `daemon` | `reaper` | `system` | `agent:<session>`.
 */
actor: string, summary: string, detail: JsonValue, };
