// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventRecord } from "./EventRecord";

/**
 * A keyset page. Pass the last row's `id` back as `before` for the next one.
 */
export type EventPage = { events: Array<EventRecord>, has_more: boolean, };
