// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session_id` is set when the adapter accepts a pre-minted id.
 */
export type ForkResponse = { command_id: string, status: string, session_id?: string | null, };
