// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForkMode } from "./ForkMode";

export type ForkExtract = { mode: ForkMode, 
/**
 * For `up_to` / `after`.
 */
anchor_message_id?: string | null, 
/**
 * For `selected`.
 */
selected_message_ids?: Array<string>, };
