// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset-fork slice, anchored on assistant `message_id`s.
 */
export type ForkMode = "up_to" | "after" | "selected";
