// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForkMode } from "./ForkMode";

/**
 * Conversation-extract selector for a subset fork.
 */
export type ForkExtract = { mode: ForkMode, 
/**
 * Anchor assistant `message_id` for `up_to`/`after`.
 */
anchor_message_id?: string | null, 
/**
 * Selected assistant `message_id`s for `selected`.
 */
selected_message_ids?: Array<string>, };
