// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `POST /api/v1/sessions/{id}/fork`.
 *
 * Like
 * [`SpawnResponse`] but also returns the child `session_id` the server
 * pre-minted (when the adapter supports a caller-supplied id, i.e. claude) so
 * the webui can navigate to the new conversation immediately instead of
 * waiting for the next roster poll to discover it.
 */
export type ForkResponse = { command_id: string, status: string, session_id: string | null, };
