// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForkExtract } from "./ForkExtract";

/**
 * Omitted fields inherit from the parent; working dir, adapter and account always do.
 */
export type ForkRequest = { model?: string | null, effort?: string | null, prompt?: string | null, name?: string | null, 
/**
 * Fork only a slice of history. Claude only.
 */
extract?: ForkExtract | null, };
