// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which slice of a parent conversation a subset fork keeps.
 *
 * All modes anchor on an assistant `message_id` (`msg_…`) — the only
 * per-message identity present in both the webui line and the on-disk
 * transcript.
 */
export type ForkMode = "up_to" | "after" | "selected";
