// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the daemon knows about gateway routing for this session. The
 * authoritative account binding lives server-side (see
 * [`SessionDiagnoseResponse::server`]).
 */
export type GatewayStatus = { 
/**
 * Whether the daemon has an authenticated server client + machine key
 * for the launch-time gateway-env pull (CCT-460).
 */
server_configured: boolean, };
