// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The GitHub integration's capability, as seen by the webui.
 */
export type GithubCapability = { 
/**
 * `true` only when the crate is compiled in **and** the `github` schema
 * exists **and** at least one connector is configured. A feature-on build
 * with no connector reports `false`; a feature-off build always reports
 * `false`.
 */
enabled: boolean, 
/**
 * `owner/name` slugs the integration tracks (empty until a later GH-*
 * story populates them).
 */
repos: Array<string>, };
