// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which credential kind a connector holds. Recorded so the UI can label the
 * connector and so a future webhook/reconcile path knows how to use the token.
 */
export type GithubCredentialKind = "pat" | "app_installation";
