// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Locator for what to refetch; never carries row bodies or credentials.
 */
export type GithubEventPayload = { connector_id: string, repo: string, 
/**
 * `None` for SHA-keyed checks.
 */
pull_number?: number | null, };
