// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Object kind a [`crate::ws::ServerEvent::GithubEvent`] refers to.
 */
export type GithubEventKind = "pull" | "check" | "review" | "review_thread" | "review_comment";
