// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Credential-free locator for the GitHub object a
 * [`crate::ws::ServerEvent::GithubEvent`] refers to.
 *
 * Deliberately minimal: enough for the client to know which PR/repo to
 * refetch over HTTP, never the row body, a token, or a raw webhook payload.
 * `pull_number` is `None` for object kinds (currently `Check`) keyed on a head
 * SHA rather than a PR number; the client maps the SHA to a PR via its cache.
 */
export type GithubEventPayload = { 
/**
 * The connector that produced the change, so multi-account clients can
 * scope the refresh.
 */
connector_id: string, 
/**
 * `owner/name` slug the object lives in.
 */
repo: string, 
/**
 * The affected PR number, when the object is PR-scoped. `None` for
 * SHA-keyed checks.
 */
pull_number?: number | null, };
