// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which GitHub object kind a [`crate::ws::ServerEvent::GithubEvent`] is about.
 *
 * One value per `*Upsert` store function, so the inbox can route a change to
 * the right view without inspecting the payload shape.
 */
export type GithubEventKind = "pull" | "check" | "review" | "review_thread" | "review_comment";
