// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reply payload of `GET /api/v1/machines/{id}/fs/gitinfo` and of the
 * daemon's `GitInfoResult` frame.
 */
export type GitInfo = { 
/**
 * `false` when `path` has no `.git` → every other field is empty.
 */
is_repo: boolean, 
/**
 * Checked-out branch (`refs/heads/` stripped); `None` when detached.
 */
branch?: string | null, 
/**
 * Full commit SHA when HEAD is detached.
 */
detached_sha?: string | null, 
/**
 * `Some` only when the caller asked for it (`git status --porcelain`).
 */
dirty?: boolean | null, 
/**
 * `.git` is a `gitdir:` file — a linked worktree, not the main checkout.
 */
is_worktree: boolean, };
