// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/v1/{resource_type}/{id}/shares` payload. `user` is the grantee,
 * accepted as either a UUID or a login (`users.name`). `action` defaults to
 * `use` (the only action today).
 */
export type GrantShare = { user: string, action?: string, };
