// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a harness can do, as the clients gate their controls on it.
 */
export type HarnessCapabilities = { fork: boolean, rename: boolean, resume: boolean, set_model: boolean, live_view: boolean, attach: boolean, mid_chat_files: boolean, child_spawn: boolean, };
