// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessCapabilities } from "./HarnessCapabilities";
import type { ModelsSource } from "./ModelsSource";
import type { PermissionMode } from "./PermissionMode";
import type { ProviderFamily } from "./ProviderFamily";

/**
 * One harness as served by `GET /api/v1/harnesses`.
 */
export type HarnessDescriptor = { id: string, label: string, family: ProviderFamily, capabilities: HarnessCapabilities, 
/**
 * Runs on every machine without an `adapters_enabled` row.
 */
default_enabled: boolean, models_source: ModelsSource, 
/**
 * The postures the harness can express, in picker order.
 */
permission_modes: Array<PermissionMode>, };
