// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessVersion } from "./HarnessVersion";

/**
 * Versions per harness, keyed by adapter id (`claude-code`, `codex`,
 * `gemini`, …). A daemon from before the map sent two fixed fields; its
 * `claude_code` key is read as `claude-code`.
 */
export type HarnessVersions = { [key in string]: HarnessVersion };
