// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelOption } from "./ModelOption";

/**
 * Body of `GET /api/v1/models/{harness}`.
 */
export type HarnessModels = { harness: string, models: Array<ModelOption>, 
/**
 * Effort levels, `""` (the harness default) first. Empty when the harness
 * has no effort dial.
 */
efforts: Array<string>, };
