// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Empty cells are omitted.
 */
export type HeatmapCell = { 
/**
 * 0 = Sunday.
 */
dow: number, hour: number, messages: number, output: number, };
