// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hour-of-week cell of the Overview activity heatmap (CCT-707). Extracted
 * in the reporting timezone; cells with no activity are absent (the grid is
 * filled client-side).
 */
export type HeatmapCell = { 
/**
 * Day of week, 0=Sunday..6=Saturday (Postgres `EXTRACT(dow …)`).
 */
dow: number, 
/**
 * Hour of day, 0..23.
 */
hour: number, 
/**
 * Assistant messages in the cell.
 */
messages: number, 
/**
 * Generated (output) tokens in the cell.
 */
output: number, };
