// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The most recent ask/permission/plan hook delivery for the session.
 */
export type HookEvent = { 
/**
 * Hook line kind: `ask`, `resolved`, `plan`, `plan_resolved`,
 * `perm-request`.
 */
kind: string, };
