// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One unresolved incident, as much of it as a badge can use.
 */
export type IncidentSummary = { name: string, 
/**
 * `none` | `minor` | `major` | `critical`.
 */
impact: string, 
/**
 * Short public link to the incident, when the page gives one.
 */
url?: string | null, };
