// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalized severity of an upstream family. `Unknown` is a first-class state:
 * no reading yet, or a reading we could not parse.
 */
export type Indicator = "unknown" | "none" | "minor" | "major" | "critical";
