// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceUpdateRequest = { 
/**
 * New deployment name. Empty / whitespace-only clears it.
 */
name: string | null, };
