// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstanceInfo = { 
/**
 * The deployment label, `null` when unset (the default).
 */
name: string | null, };
