// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache keep-alive: one tick every `interval_secs` while idle, stopping after
 * `max_ticks` (`0` = never). Human activity resets `ticks_sent`.
 */
export type KeepaliveState = { interval_secs: number, max_ticks: number, ticks_sent: number, 
/**
 * `None` when indefinite.
 */
until?: string | null, };
