// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `color` is a CSS hex string.
 */
export type Label = { id: string, name: string, color: string, };
