// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable, user-defined colored label.
 *
 * Labels are global (shared
 * across sessions) and attached many-to-many; `color` is a CSS hex string
 * (e.g. `"#e11d48"`) chosen via the label picker's swatches/color input.
 */
export type Label = { id: string, name: string, color: string, };
