// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Label } from "./Label";

/**
 * Response for `GET /api/v1/labels` — every label known to the server.
 */
export type LabelListResponse = { labels: Array<Label>, };
