// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Langfuse read integration's capability, as seen by the webui (CCT-564).
 * `available` gates every Langfuse UI element; `host` + `project_id` build the
 * `<host>/project/<id>/sessions/<uuid>` deep link. All `None` when the sink is
 * unconfigured; `project_id` alone `None` when the id could not be resolved.
 */
export type LangfuseCapability = { available: boolean, host: string | null, project_id: string | null, };
