// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cost + `trace_count` are exact off the traces list; token classes are
 * best-effort — only populated when the deployment carries per-trace
 * `usageDetails` (legacy self-hosted trace lists often don't).
 */
export type LangfuseSessionUsage = { cost_usd: number, input_tokens: number, output_tokens: number, cache_read: number, trace_count: number, };
