// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/v1/sessions/{id}/launch` — promote a draft
 * session to a live spawn.
 *
 * The stored draft holds prompt + config only; env
 * secrets are entered fresh here (never persisted at rest) and account gateway
 * tokens are minted at launch so they're never stale. An empty map is fine for
 * drafts that need no manual secrets.
 */
export type LaunchRequest = { env?: { [key in string]: string }, };
