// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/v1/sessions/{id}/launch`; env is entered fresh, never stored.
 */
export type LaunchRequest = { env?: { [key in string]: string }, };
