// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the account's latest usage payload says about a limit reset, normalized
 * across providers for the button in the usage row.
 */
export type LimitResetStatus = { 
/**
 * `codex` (reset credits) or `claude` (`juniper_tide`).
 */
kind: "codex" | "claude", 
/**
 * Whether a claim would do anything right now.
 */
available: boolean, 
/**
 * Codex: the redeemable credit's title (e.g. "Full reset (Weekly + 5 hr)").
 */
title: string | null, 
/**
 * Codex: the credit a claim would name.
 */
credit_id: string | null, 
/**
 * Claude: why the reset cannot be claimed (e.g. `not_at_wall`).
 */
ineligible_reason: string | null, next_available_at: string | null, weekly_resets_at: string | null, };
