// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LimitResetResponse = { account_id: string, provider: string, 
/**
 * Upstream outcome verbatim (`snake_case`), `error` when the call failed, or
 * `unconfirmed` when it succeeded with a body we could not read.
 */
outcome: string, credit_id: string | null, next_available_at: string | null, weekly_resets_at: string | null, idempotency_key: string, 
/**
 * The click matched a prior attempt and no new consume request was sent.
 */
reused: boolean, };
