// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One self-hosted Claude model the server offers, mirrored to the webui's spawn
 * picker (CCT-LITELLM). `model` is the `--model` code; `label` is the display
 * name. Present only when the operator configured both an endpoint and a model
 * list (otherwise the list is empty and the picker shows only native families).
 * The endpoint URL and its auth token are deliberately NOT exposed — they're
 * injected server-side at spawn.
 */
export type LiteLlmModelInfo = { model: string, label: string, };
