// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse liveness tier for the sessions-list status dot.
 *
 * Derived purely from the age of the last heartbeat; orthogonal to
 * [`SessionStatus`] — it answers "is this still warm?" not "what lifecycle
 * state".
 *
 * - `Active`: heartbeat within the active window (green dot).
 * - `Stale`: alive but quiet — past the active window (orange dot).
 * - `Dead`: long inactive (no dot).
 */
export type Liveness = "active" | "stale" | "dead";
