// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coarse liveness tier for a machine (its daemon's WS).
 *
 * Derived from the age
 * of `machines.last_seen_at`, which the server now advances on every daemon
 * `Heartbeat` frame (CCT-255). Mirrors the session [`Liveness`] tiers but
 * names them in machine terms:
 *
 * - `Online`: a heartbeat arrived within the active window.
 * - `Stale`: quiet but not yet declared dead — past the active window.
 * - `Offline`: no heartbeat for the full dead window (daemon gone).
 */
export type MachineLiveness = "online" | "stale" | "offline";
