// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One harness as a machine sees it.
 */
export type MachineAdapterInfo = { adapter_id: string, 
/**
 * Whether the daemon runs this harness after the next reconcile.
 */
enabled: boolean, 
/**
 * Per-machine adapter config the daemon receives; `{}` when nothing is set.
 */
config: Record<string, unknown>, 
/**
 * Whether an `adapters_enabled` row exists; without one, `enabled` is the
 * harness's `default_enabled`.
 */
pinned: boolean, default_enabled: boolean, };
