// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MachineRow = { id: string, user_id: string, name: string, display_name: string | null, first_seen_at: string, last_seen_at: string, revoked_at: string | null, 
/**
 * `persistent` (a real daemon) or `ephemeral` (a dispatch/worker pod).
 * The New-session picker hides `ephemeral` machines (CCT-183).
 */
kind: string, 
/**
 * Operator-set badge hue (0-359, CCT-222). `None` = hash of the name.
 */
hue: number | null, };
