// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Last-known host resource usage of one machine. Percentages are 0..=100.
 */
export type MachineResources = { 
/**
 * CPU busy share over the last heartbeat interval, 0..=100, across all
 * cores (a 4-core box with one saturated core reads 25).
 */
cpu_pct: number, 
/**
 * Memory in use (total minus the kernel's `MemAvailable`), 0..=100.
 */
mem_pct: number, mem_used_bytes: number, mem_total_bytes: number, 
/**
 * Fill of the filesystem holding the daemon's home directory, 0..=100.
 */
disk_pct: number, disk_used_bytes: number, disk_total_bytes: number, 
/**
 * The path the disk figures were sampled at (the daemon's home dir).
 */
disk_path: string, 
/**
 * 1-minute load average when the host reports one.
 */
load1?: number | null, };
