// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MachineLiveness } from "./MachineLiveness";
import type { MachineResources } from "./MachineResources";

/**
 * One enrolled daemon machine and its last-known resource snapshot, for the
 * Settings › Resource monitoring list and the header gauge.
 */
export type MachineResourcesRow = { machine_id: string, name: string, display_name: string | null, 
/**
 * Operator-set badge hue (0-359). `None` = hash of the name.
 */
hue: number | null, liveness: MachineLiveness, 
/**
 * When the daemon was last heard from. The tier above is derived from this,
 * but a reader that wants to show an age needs the stamp itself.
 */
last_seen_at: string, 
/**
 * `None` until the machine's daemon has sent a heartbeat carrying a
 * snapshot (older daemon, non-Linux host): the gauge shows "?" then.
 */
resources: MachineResources | null, updated_at: string | null, };
