// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST .../{number}/mark-viewed` and `.../unmark-viewed` —
 * the file path plus the blob SHA the reviewer saw. The path is the per-file
 * identity; the blob SHA is the content the mark is keyed to.
 */
export type MarkViewedRequest = { 
/**
 * Head-side file path being (un)marked.
 */
path: string, 
/**
 * The blob SHA the reviewer saw for this path (from `DiffFile.blob_sha`).
 * Required on mark; ignored on unmark (the path is the identity there).
 */
blob_sha: string | null, };
