// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `mark-viewed` / `unmark-viewed`.
 */
export type MarkViewedRequest = { path: string, 
/**
 * Required on mark, ignored on unmark.
 */
blob_sha?: string | null, };
