// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MeResponse = { 
/**
 * `admin` | `user` | `machine`.
 */
role: string, user_id: string | null, 
/**
 * Resolved from `users.name` when the token maps to a user.
 */
user_name: string | null, machine_id: string | null, 
/**
 * Non-secret fragment of the token this request authenticated with,
 * e.g. `cctui_u_ab1234…ef34`.
 */
token_preview: string, };
