// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageRequest = { content: string, 
/**
 * Client-minted `UUIDv7` echoed on every event of the turn.
 */
turn_id?: string | null, 
/**
 * RFC3339, at most 30 days ahead; the request is queued and returns 202.
 */
deliver_at?: string | null, };
