// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `seq` is the `stream_events.id` insert sequence: the only stable address of
 * a message (`ts` collides).
 */
export type MessagePin = { session_id: string, seq: number, message_id: string | null, note: string | null, created_at: string, };
