// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MintTokenResponse = { token: string, label: string | null, expires_at: string | null, };
