// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MintKeyRequest = { label: string | null, 
/**
 * Scopes to grant — must be ⊆ the owner's ceiling (enforced server-side).
 */
scopes: Array<string>, expires_at: string | null, };
