// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MintKeyResponse = { id: string, 
/**
 * The plaintext token — returned ONCE, never recoverable after.
 */
key: string, scopes: Array<string>, };
