// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a model is annotated in the picker. The client words it.
 */
export type ModelHint = { "kind": "gated", version: string, current: string, } | { "kind": "needs_version", version: string, };
