// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-model token + message totals over the reporting range (CCT-707).
 *
 * Model attribution is session-level (`sessions.model`); per-turn model
 * accuracy is out of scope. Sessions with no recorded model bucket under
 * `"unknown"`.
 */
export type ModelUsage = { 
/**
 * `sessions.model`, or `"unknown"` when the session has no model recorded.
 */
model: string, 
/**
 * Non-cached prompt tokens attributed to the model.
 */
input: number, 
/**
 * Generated tokens attributed to the model.
 */
output: number, 
/**
 * Prompt-cache read tokens attributed to the model.
 */
cache_read: number, 
/**
 * Assistant messages (rows) attributed to the model.
 */
messages: number, };
