// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attributed by session model, not per turn.
 */
export type ModelUsage = { 
/**
 * `"unknown"` when unrecorded.
 */
model: string, input: number, output: number, cache_read: number, 
/**
 * Assistant messages.
 */
messages: number, };
