// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a harness's model picker gets its entries.
 */
export type ModelsSource = "static" | "catalog" | "none";
