// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelHint } from "./ModelHint";

/**
 * One entry of a model picker. `v` is the wire value; the empty string means
 * "leave the harness its own default".
 */
export type ModelOption = { v: string, label: string, hint?: ModelHint, disabled: boolean, };
