// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountProvider } from "./AccountProvider";

/**
 * API view of an account identity: name, owner, timestamps, and its
 * provider credentials.
 */
export type OAuthAccount = { id: string, name: string, 
/**
 * Owner-chosen identity glyph: one emoji grapheme, or NULL for the
 * generated letter square.
 */
emoji: string | null, 
/**
 * Owning user — admins see all accounts, so the owner matters.
 */
user_id: string, 
/**
 * Owner's name for display, joined from `users`.
 */
user_name: string | null, created_at: string, updated_at: string, providers: Array<AccountProvider>, 
/**
 * The owner's veto on pool membership: with this false, only the owner
 * may enrol this account in an account pool. Grantees can still launch on
 * it by name — they just cannot make it a silent overflow target.
 */
pool_eligible: boolean, 
/**
 * Relative plan size inside a pool aggregate (upstream reports percent,
 * never the plan behind it). `1` = same as the other members.
 */
pool_weight: number, 
/**
 * Names (only) of the account's free-form extra env vars, sorted.
 * Values stay WRITE-ONLY (encrypted, never returned) — the names let the UI
 * show what is currently set with a replace-on-save affordance.
 */
env_names: Array<string>, };
