// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuthFinish = { nonce: string, 
/**
 * New-account name. Required unless the flow was started with an
 * `account_id` attach target (then ignored).
 */
name?: string, 
/**
 * anthropic: the `code#state` pair pasted from claude.ai (the `#state`
 * suffix is optional). Either this or `callback_url` must be present.
 */
code?: string, 
/**
 * openai/Codex: the full `http://localhost:1455/auth/callback?code=…&state=…`
 * URL the user copies from the browser address bar after the redirect fails
 * to load (the fixed redirect can't reach cctui).
 */
callback_url?: string, };
