// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyConfig = { 
/**
 * Whether this server can run a passkey ceremony at all (relying party
 * configured). False means the login screen shows only the token box.
 */
available: boolean, 
/**
 * Whether anyone has enrolled a key. The login screen offers the passkey
 * button only when a ceremony could actually succeed.
 */
enrolled: boolean, 
/**
 * Server-wide admin setting: attempt the passkey read as soon as the login
 * screen opens instead of waiting for a click. The user can always dismiss
 * it and type a token.
 */
auto_prompt: boolean, };
