// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyTestResult = { 
/**
 * The label of the key that answered, so the UI can say which one.
 */
label: string, };
