// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PasskeyRegisterFinish = { challenge_id: string, 
/**
 * Human label for the key ("iPhone", "YubiKey", "Bitwarden").
 */
label: string | null, 
/**
 * The `PublicKeyCredential` from `navigator.credentials.create()`.
 */
credential: JsonValue, 
/**
 * `credProps.rk` as the browser reported it, when it did. `false` means
 * the key is not discoverable and so cannot drive the usernameless login.
 */
discoverable: boolean | null, };
