// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PasskeyChallenge = { 
/**
 * Handle for the parked ceremony state; echoed back on finish.
 */
challenge_id: string, 
/**
 * The raw WebAuthn options, passed to `navigator.credentials.*` verbatim
 * after the browser-side base64url decoding. Deliberately untyped here:
 * the shape is the W3C one and webauthn-rs owns it.
 */
options: JsonValue, };
