// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyRow = { id: string, label: string, 
/**
 * False when the authenticator declined to store a discoverable
 * credential: the key still works as a second factor but will not appear
 * at the login screen, and the UI says so.
 */
discoverable: boolean, created_at: string, last_used_at: string | null, };
