// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live ask/permission prompt state for the session.
 */
export type PendingPrompts = { 
/**
 * An `AskUserQuestion`/plan form is up in the worker PTY.
 */
pending_ask: boolean, 
/**
 * A blocking `PreToolUse` permission hook is parked awaiting a decision.
 */
parked_perm_hook: boolean, 
/**
 * The control socket's `needs` string for a pending tool-permission
 * prompt, when one is up.
 */
control_needs: string | null, 
/**
 * The synthesized `request_id` of the pending permission prompt.
 */
perm_request_id: string | null, };
