// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-spawn permission posture (CCT-149, supersedes the CCT-139
 * `full_access: bool`). Adapters map it to their own vocabulary; `None`
 * on a [`SessionSpec`] defers to the daemon's per-host default.
 */
export type PermissionMode = "yolo" | "auto" | "ask";
