// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One answer an agent offers on a permission prompt.
 */
export type PermissionChoice = { option_id: string, name: string, 
/**
 * `allow_once` / `allow_always` / `reject_once` / `reject_always`.
 */
kind: string, };
