// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceSetting } from "./PluginInstanceSetting";

/**
 * The admin settings form for one plugin. Secret values are represented only
 * by `secrets_set`.
 */
export type PluginInstanceSettings = { id: string, instance_settings: Array<PluginInstanceSetting>, values: { [key in string]: string }, secrets_set: { [key in string]: boolean }, 
/**
 * The `instanceSettings` key the backend proxy reads the upstream from.
 */
backend_upstream_setting: string | null, 
/**
 * Whether a proxy secret exists; its value is only ever shown at rotation.
 */
proxy_secret_set: boolean, };
