// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginInstanceSettingsRequest = { 
/**
 * Keys to write. An empty value clears the setting; omitted keys keep
 * their current value.
 */
values: { [key in string]: string }, };
