// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginBackend = { 
/**
 * The `instanceSettings` key holding the upstream base URL.
 */
upstreamSetting: string, };
