// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One instance-level setting. `secret` values are sealed at rest and never
 * leave the server, not even to the admin who wrote them.
 */
export type PluginInstanceSetting = { key: string, label: string, type: string, secret: boolean, };
