// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginSetting } from "./PluginSetting";

export type PluginInfo = { id: string, name: string, description: string, version: string, 
/**
 * Tsumikit icon name, when the manifest declares one.
 */
icon: string | null, 
/**
 * `/plugins/<id>/<web>?v=<sha8>`, absent for skills-only plugins.
 */
web: string | null, skills: Array<string>, 
/**
 * From the caller's settings `plugins.enabled[id]`.
 */
enabled: boolean, 
/**
 * Per-user settings the plugin declares.
 */
settings: Array<PluginSetting>, 
/**
 * The caller's current values, by setting key (`plugins.config[id]`).
 */
config: { [key in string]: string }, };
