// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Install a published plugin by catalog id; the server resolves its url and
 * sha256 itself and never trusts client-supplied ones.
 */
export type PluginCatalogInstallRequest = { catalog: string, };
