// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A rotated proxy secret, returned exactly once.
 */
export type PluginProxySecret = { id: string, secret: string, };
