// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginPage = { title: string, 
/**
 * Tsumikit icon name for the nav entry.
 */
icon?: string | null, };
