// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The env name a host-minted, `read`-scoped cctui token is exported under.
 *
 * There is deliberately no scope field: the one cctui API a plugin's skill can reach is its own
 * backend proxy, which asks for `read`.
 */
export type PluginHostToken = { env: string, };
