// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceSetting } from "./PluginInstanceSetting";
import type { PluginPage } from "./PluginPage";
import type { PluginSetting } from "./PluginSetting";

export type PluginInfo = { id: string, name: string, description: string, version: string, 
/**
 * Tsumikit icon name, when the manifest declares one.
 */
icon: string | null, 
/**
 * `/plugins/<id>/<web>?v=<sha8>`, absent for skills-only plugins.
 */
web: string | null, 
/**
 * Present when the plugin contributes a full page at `/apps/<id>`.
 */
page: PluginPage | null, 
/**
 * Stylesheets to load with the module, as `/plugins/<id>/<path>?v=<sha8>`.
 */
styles: Array<string>, skills: Array<string>, 
/**
 * From the caller's settings `plugins.enabled[id]`.
 */
enabled: boolean, 
/**
 * Per-user settings the plugin declares.
 */
settings: Array<PluginSetting>, 
/**
 * The caller's current values, by setting key (`plugins.config[id]`).
 */
config: { [key in string]: string }, 
/**
 * Instance-level settings the admin owns, for display only.
 */
instanceSettings: Array<PluginInstanceSetting>, 
/**
 * Non-secret instance values, and only for a caller who enabled the
 * plugin. Secrets are never included.
 */
instanceSettingValues: { [key in string]: string }, 
/**
 * The plugin's backend is reachable at `/api/v1/plugins/<id>/backend/`.
 */
backend: boolean, };
