// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-key exposure policy. Ordered least → most restrictive for display.
 */
export type Policy = "safe" | "care" | "managed" | "system";
