// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PoolUsageMember = { account_id: string, name: string, emoji: string | null, 
/**
 * `accounts.pool_weight`.
 */
weight: number, 
/**
 * False when the credential's usage could not be read: absent from the
 * aggregate rather than counted as empty or as full.
 */
usage_known: boolean, };
