// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolProjection } from "./PoolProjection";
import type { PoolUsageWindowMember } from "./PoolUsageWindowMember";

/**
 * One window of a pool family, aggregated.
 */
export type PoolUsageWindow = { key: string, kind: string, label: string, model_display_name: string | null, 
/**
 * Weighted mean utilization.
 */
level_pct: number, 
/**
 * Weighted mean of what an even spend would show now.
 */
expected_pct: number, 
/**
 * `level / expected`, the pool's burn against its linear budget; `None`
 * on a window too young to rate.
 */
ratio: number | null, 
/**
 * Nearest reset among the members.
 */
next_reset_at: string | null, members: Array<PoolUsageWindowMember>, projection: PoolProjection | null, 
/**
 * Set exactly when `projection` is `None`.
 */
projection_unavailable: string | null, };
