// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolFamilyUsage } from "./PoolFamilyUsage";

/**
 * A pool's quota, aggregated per provider family — what the pool zone and
 * the stats panel render. See [`crate::pool_usage`] for the arithmetic.
 */
export type PoolUsageView = { pool_id: string, name: string, strategy: string, 
/**
 * Off means a projection only speaks for launches: a live session stays
 * on its member and hits that member's wall.
 */
failover: boolean, families: Array<PoolFamilyUsage>, };
