// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the pool runs out under measured rates.
 */
export type PoolProjection = { 
/**
 * Every member at 100% at once; `None` when that never happens inside the
 * horizon (a reset always comes first).
 */
wall_at: string | null, 
/**
 * The first member to hit 100%, which matters when failover is off.
 */
first_member_wall_at: string | null, 
/**
 * Sum of the members' measured rates, in percent points per hour.
 */
demand_pct_per_hour: number, 
/**
 * Shortest slope base among the members, in hours.
 */
slope_hours: number, 
/**
 * Lowest weighted mean headroom reached inside the horizon.
 */
min_margin_pct: number, };
