// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolUsageMember } from "./PoolUsageMember";
import type { PoolUsageWindow } from "./PoolUsageWindow";

/**
 * One provider family inside a pool: only its members are interchangeable
 * (a claude-code spawn elects among the anthropic credentials, a codex spawn
 * among the openai ones), so only they are aggregated together.
 */
export type PoolFamilyUsage = { 
/**
 * `anthropic` | `openai` | `fireworks`.
 */
family: string, members: Array<PoolUsageMember>, windows: Array<PoolUsageWindow>, };
