// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A member's share of one aggregated window.
 */
export type PoolUsageWindowMember = { account_id: string, utilization: number, resets_at: string | null, expected_pct: number | null, ratio: number | null, };
