// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A named bundle of settings + env applied together (e.g. "Quiet defaults").
 */
export type Preset = { 
/**
 * Stable id (e.g. `"quiet-defaults"`).
 */
id: string, 
/**
 * Display name.
 */
name: string, 
/**
 * What it does / caveats.
 */
description: string, 
/**
 * `settings.json` fragment this preset writes.
 */
settings: { [key in string]?: JsonValue }, 
/**
 * Env fragment this preset writes.
 */
env: { [key in string]?: string }, };
