// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewTicket = { ticket: string, 
/**
 * Absolute URL that redeems the ticket and lands on the preview.
 */
authUrl: string, expiresInSecs: number, };
