// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanCategory } from "./ScanCategory";

export type PrivacyScanJob = { id: string, 
/**
 * `running` | `completed` | `cancelled` | `failed`.
 */
status: string, dry_run: boolean, cancel_requested: boolean, rows_total: number | null, rows_scanned: number, rows_changed: number, substitutions: number, by_category: { [key in string]: number }, categories: Array<ScanCategory>, error: string | null, created_at: string, finished_at: string | null, };
