// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The knobs a profile carries. The account pick is at most one of
 * `account_id` / `pool_id` / `no_account`; none = Auto (the server elects one).
 * `None` model / effort / permission mode = the harness or account default.
 */
export type ProfileSpec = { harness: string, account_id?: string | null, pool_id?: string | null, no_account?: boolean, model_alias?: string | null, effort?: string | null, permission_mode?: string | null, };
