// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The knobs a profile carries. `None` account = Auto (the server elects one);
 * `None` model / effort / permission mode = the harness or account default.
 */
export type ProfileSpec = { harness: string, account_id?: string | null, model_alias?: string | null, effort?: string | null, permission_mode?: string | null, };
