// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Prompt = { id: string, name: string, content: string, description: string | null, 
/**
 * Purpose tag: `general` (default) or `review` (a "Review with agent"
 * prompt). The resolver filters on this so review-prompt scoping never
 * collides with ordinary prompts.
 */
kind: string, 
/**
 * GitHub owner this prompt is scoped to, or `None` for a global prompt.
 */
scope_owner: string | null, 
/**
 * Repo name (within `scope_owner`) this prompt is scoped to. Requires
 * `scope_owner`; `None` means owner-wide (or global, when owner is also
 * `None`).
 */
scope_repo: string | null, created_at: string, updated_at: string, };
