// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderFamily } from "./ProviderFamily";

/**
 * One selectable provider kind, in the order the pickers list them.
 */
export type ProviderInfo = { id: string, 
/**
 * Short display name (`anthropic` → `Claude`).
 */
label: string, 
/**
 * Longer form the provider pickers list.
 */
picker_label: string, family: ProviderFamily, 
/**
 * Whether the credential is a static key the gateway forwards (no OAuth).
 */
static_credential: boolean, };
