// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DegradedComponent } from "./DegradedComponent";
import type { IncidentSummary } from "./IncidentSummary";
import type { ProviderIndicator } from "./ProviderIndicator";

/**
 * What a client gets for one family. Serializable and cheap to clone: it is
 * embedded in every usage row.
 */
export type ProviderStatus = { 
/**
 * `anthropic` | `openai`.
 */
family: string, indicator: ProviderIndicator, 
/**
 * The provider's own one-liner ("All Systems Operational"), empty when the
 * page gave none.
 */
description: string, 
/**
 * The human status page, so a badge can link somewhere useful.
 */
url: string, components: Array<DegradedComponent>, incidents: Array<IncidentSummary>, 
/**
 * When the poller last got an answer (a 304 counts). `None` ⇒ never.
 */
checked_at?: string | null, };
