// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account may hold at most one provider per family; mirrors the server's
 * generated `family` column.
 */
export type ProviderFamily = "anthropic" | "openai" | "fireworks";
