// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY output freshness/throughput sensed by the held-attach drain loop:
 * the second, hook-independent activity signal. `missing` until
 * the drain loop has read bytes for the session.
 */
export type PtyOutputStats = { last_output_age_ms?: number | null, recent_bytes_per_min?: number | null, };
