// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY output freshness/throughput. Slot only — the sensing depends on
 * CCT-546 (PTY output capture), which has not landed; until then the fact is
 * always `missing`.
 */
export type PtyOutputStats = { last_output_age_ms: number | null, recent_bytes_per_min: number | null, };
