// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Publishes a draft as one batched GitHub review.
 */
export type PublishReviewRequest = { draft_id: string, 
/**
 * Review body.
 */
summary?: string | null, 
/**
 * Refuse to publish if the PR head differs. `None` skips the check.
 */
expected_head_sha?: string | null, };
