// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedComment } from "./SkippedComment";

export type PublishReviewResult = { review_id: number, submitted: number, skipped: Array<SkippedComment>, };
