// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedComment } from "./SkippedComment";

/**
 * Outcome of a successful publish: the GitHub review id, how many comments were
 * submitted, and which draft comments were skipped (un-anchorable).
 */
export type PublishReviewResult = { 
/**
 * GitHub's submitted review id.
 */
review_id: number, 
/**
 * How many comments were included in the batched submission.
 */
submitted: number, 
/**
 * Draft comments left out because their anchor no longer resolved.
 */
skipped: Array<SkippedComment>, };
