// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `POST .../{number}/publish-review` — publish a draft as one
 * batched GitHub review. The draft (and its verdict) is named by `draft_id`; an
 * optional `summary` becomes the review body.
 */
export type PublishReviewRequest = { 
/**
 * The open draft to publish.
 */
draft_id: string, 
/**
 * Optional review summary (the `body` of the submitted review).
 */
summary: string | null, 
/**
 * The head SHA the reviewer was viewing the diff against when they hit
 * Publish. The server compares it to the PR's *current* head SHA; a mismatch
 * means the PR was force-pushed/rebased since the draft was authored, so the
 * publish is refused (rather than mis-placing comments onto rotated lines).
 * `None` skips the guard (the caller accepts re-anchoring against current).
 */
expected_head_sha: string | null, };
