// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffFile } from "./DiffFile";

/**
 * Structured PR diff, cached server-side by `head_sha`.
 */
export type PullDiff = { repo: string, number: number, head_sha: string, 
/**
 * Whole-PR count, even when `huge` caps `files`.
 */
total_files: number, 
/**
 * Additions + deletions.
 */
total_changes: number, 
/**
 * Over the large-diff threshold; `files` is capped.
 */
huge: boolean, files: Array<DiffFile>, };
