// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed PR, keyed on `(connector, repo, number)`.
 */
export type PullUpsert = { 
/**
 * GraphQL node id.
 */
node_id: string, repo: string, number: number, title: string, 
/**
 * `open` | `closed`.
 */
state: string, merged: boolean, draft: boolean, 
/**
 * `None` until GitHub computes it.
 */
mergeable_state: string | null, author: string, head_sha: string, base_ref: string, head_ref: string, 
/**
 * ISO-8601.
 */
gh_created_at: string, 
/**
 * ISO-8601.
 */
gh_updated_at: string, };
