// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffFile } from "./DiffFile";

/**
 * The structured diff for one PR, returned by `pulls/{ref}/diff`.
 *
 * Cached server-side keyed on `head_sha`, so a repeated load of an unchanged
 * PR is served from memory with no GitHub round-trip (docs §6.2). When the head
 * SHA rotates (a new push), the cache entry is naturally superseded.
 */
export type PullDiff = { repo: string, number: number, 
/**
 * The head SHA this diff was computed against (the cache key).
 */
head_sha: string, 
/**
 * Total changed-file count across the whole PR (even when `huge` truncates
 * `files`), so the UI can show "showing N of M files".
 */
total_files: number, 
/**
 * Total changed-line count (additions + deletions) across the PR.
 */
total_changes: number, 
/**
 * `true` when the PR exceeds the large-diff threshold (docs §11, the
 * 100k-plus-line case GitHub serves unreliably): `files` is then capped and
 * the webui shows a "huge diff" affordance / per-file lazy load instead of
 * rendering everything at once.
 */
huge: boolean, files: Array<DiffFile>, };
