// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionBucket } from "./AttentionBucket";
import type { CheckSummary } from "./CheckSummary";
import type { ReviewSummary } from "./ReviewSummary";

export type PullInboxItem = { connector_id: string, repo: string, number: number, title: string, 
/**
 * `open` | `closed`.
 */
state: string, merged: boolean, draft: boolean, author: string, head_ref: string, base_ref: string, mergeable_state: string | null, 
/**
 * ISO-8601; the inbox sort key.
 */
gh_updated_at: string, bucket: AttentionBucket, checks: CheckSummary, reviews: ReviewSummary, };
