// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed pull request, ready to upsert into `github.pulls`.
 *
 * Produced by both the webhook (`pull_request` event) and the reconcile poll;
 * the upsert keys on `(connector, repo, number)` so they converge on one row.
 */
export type PullUpsert = { 
/**
 * GitHub's stable global node id (GraphQL) for later API calls.
 */
node_id: string, 
/**
 * `owner/name` slug the PR lives in.
 */
repo: string, 
/**
 * The human-facing PR number within the repo.
 */
number: number, title: string, 
/**
 * `open` | `closed`.
 */
state: string, merged: boolean, draft: boolean, 
/**
 * GitHub's `mergeable_state`; `None` until GitHub computes it.
 */
mergeable_state: string | null, author: string, 
/**
 * Head commit SHA; CI checks key off this.
 */
head_sha: string, base_ref: string, head_ref: string, 
/**
 * GitHub's own creation timestamp (ISO-8601).
 */
gh_created_at: string, 
/**
 * GitHub's own last-update timestamp (ISO-8601).
 */
gh_updated_at: string, };
