// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PUT /api/v1/drafts/{key}`. An empty `text` deletes the row, so the client
 * does not have to branch between `PUT` and `DELETE` as a field is cleared.
 */
export type PutDraftRequest = { text: string, };
