// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PutRedirectRequest = { to_account?: string | null, to_model?: string, family: string, match_model?: string, until?: string | null, reason?: string, 
/**
 * The admin token has no user identity and must name the rule's owner.
 */
user_id?: string | null, };
