// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-(account, provider) rate limits. Both optional; `None` ⇒ that dimension is
 * unlimited. Persisted as `{ "rpm": int?, "tpm": int? }` on the provider row.
 */
export type RateLimits = { 
/**
 * Max requests admitted per rolling 60s window.
 */
rpm?: number | null, 
/**
 * Max tokens counted per rolling 60s window.
 */
tpm?: number | null, };
