// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelabelTokenRequest = { 
/**
 * `None`/blank clears the label.
 */
label: string | null, };
