// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One release published since the running build: tag, page and Markdown notes.
 */
export type ReleaseNote = { version: string, url: string, 
/**
 * The release body as written on GitHub (Markdown); empty when the
 * release has no description.
 */
body: string, 
/**
 * ISO-8601 publication time as GitHub reports it, `null` for drafts.
 */
published_at: string | null, };
