// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A dispatcher edit. `name` renames; each binding field is left untouched when
 * absent, cleared by an empty string, and set otherwise — so the one-control
 * UI can express "bind this pool, drop the account" in a single call.
 */
export type RenameDispatcher = { name: string, default_account?: string | null, default_pool?: string | null, };
