// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenameMachineRequest = { 
/**
 * `None` clears the override so the UI falls back to `name`.
 */
display_name: string | null, };
