// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RescrubReport = { dry_run: boolean, rows_scanned: number, rows_changed: number, substitutions: number, 
/**
 * Substitution counts keyed by category (e.g. `github_token`).
 */
by_category: { [key in string]: number }, };
