// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `POST /api/v1/settings/rescrub`: apply the caller's effective scrub
 * list to their already-stored `stream_events`. `dry_run` reports counts and
 * writes nothing; the real pass masks matching rows and is idempotent (a second
 * run reports zero changes). Optional `session_ids` / `since` scope the sweep.
 */
export type RescrubRequest = { dry_run: boolean, session_ids: Array<string> | null, since: string | null, };
