// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * API view of one live share grant. Safe to return — no secrets, just who the
 * resource is shared with and since when.
 */
export type ResourceShareInfo = { resource_type: string, resource_id: string, user_id: string, 
/**
 * The grantee's login (`users.name`), joined for display.
 */
user_name: string, action: string, granted_at: string, };
