// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pulled-down GitHub review comment (the posted side, CONN-3
 * `github.review_comments`), rendered inline alongside local drafts.
 */
export type ReviewThreadCommentInfo = { 
/**
 * GitHub's review-comment id.
 */
comment_id: number, author: string, body: string, created_at: string, };
