// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewUpsert = { repo: string, pull_number: number, review_id: number, reviewer: string, 
/**
 * `approved` | `changes_requested` | `commented` | `dismissed` | `pending`.
 */
state: string, body: string | null, commit_id: string | null, 
/**
 * ISO-8601. `None` while pending.
 */
submitted_at: string | null, };
