// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewCommentUpsert = { repo: string, pull_number: number, comment_id: number, thread_node_id: string | null, author: string, body: string, path: string | null, side: string | null, line: number | null, gh_created_at: string, gh_updated_at: string, };
