// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewThreadUpsert = { repo: string, pull_number: number, thread_node_id: string, path: string, 
/**
 * `LEFT` | `RIGHT`, when anchored.
 */
side: string | null, line: number | null, resolved: boolean, };
