// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed review thread (a conversation anchored on a diff line).
 */
export type ReviewThreadUpsert = { repo: string, pull_number: number, 
/**
 * GitHub's review-thread node id (the upsert key).
 */
thread_node_id: string, path: string, 
/**
 * `LEFT` | `RIGHT` diff side, when anchored.
 */
side: string | null, line: number | null, resolved: boolean, };
