// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewThreadCommentInfo } from "./ReviewThreadCommentInfo";

/**
 * A review thread already posted on GitHub.
 */
export type ReviewThreadInfo = { thread_node_id: string, path?: string | null, 
/**
 * `LEFT` | `RIGHT`, when anchored.
 */
side?: string | null, 
/**
 * 1-based, on `side`.
 */
line?: number | null, resolved: boolean, 
/**
 * Oldest first.
 */
comments: Array<ReviewThreadCommentInfo>, };
