// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated review state for a PR — the strongest outstanding signal plus
 * raw counts, mirroring the classifier's collapse.
 */
export type ReviewSummary = { 
/**
 * Number of submitted reviews requesting changes.
 */
changes_requested: number, 
/**
 * Number of submitted approvals.
 */
approved: number, 
/**
 * Number of plain comment reviews.
 */
commented: number, };
