// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReviewThreadCommentInfo = { comment_id: number, author: string, body: string, created_at: string, };
