// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed submitted PR review (the posted side).
 */
export type ReviewUpsert = { repo: string, pull_number: number, 
/**
 * GitHub's review id (the upsert key, scoped to the connector).
 */
review_id: number, reviewer: string, 
/**
 * `approved` | `changes_requested` | `commented` | `dismissed` | `pending`.
 */
state: string, body: string | null, commit_id: string | null, 
/**
 * ISO-8601; `None` for a pending review.
 */
submitted_at: string | null, };
