// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewThreadCommentInfo } from "./ReviewThreadCommentInfo";

/**
 * One pulled-down GitHub review thread (CONN-3 `github.review_threads`) plus its
 * comments, anchored on a diff line.
 *
 * Distinct from a local draft: it is already
 * posted on GitHub. The webui renders it inline, visually separate from drafts.
 */
export type ReviewThreadInfo = { thread_node_id: string, 
/**
 * Head-side path the thread is anchored on, when known.
 */
path?: string | null, 
/**
 * `LEFT` | `RIGHT` diff side, when anchored.
 */
side?: string | null, 
/**
 * 1-based line on `side`, when anchored.
 */
line?: number | null, resolved: boolean, 
/**
 * The thread's comments, oldest first.
 */
comments: Array<ReviewThreadCommentInfo>, };
