// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The pending review verdict a draft will submit when published (GH-VIEW-5).
 */
export type ReviewVerdict = "comment" | "approve" | "request_changes";
