// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A parsed individual review comment.
 */
export type ReviewCommentUpsert = { repo: string, pull_number: number, 
/**
 * GitHub's review-comment id (the upsert key, scoped to the connector).
 */
comment_id: number, 
/**
 * Correlates to a `review_threads` row when known.
 */
thread_node_id: string | null, author: string, body: string, path: string | null, side: string | null, line: number | null, gh_created_at: string, gh_updated_at: string, };
