// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanSample = { 
/**
 * Any value the match carries is masked; a bare match is kept whole only
 * when it cannot itself be a secret.
 */
text: string, context: string, value_follows: boolean, };
