// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanSample } from "./ScanSample";

export type ScanCategory = { category: string, count: number, samples: Array<ScanSample>, 
/**
 * Most matches of this user pattern are bare identifiers with no value
 * after them (`access_token` in prose, not a credential).
 */
identifier_warning: boolean, };
