// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScanSample = { 
/**
 * Abbreviated for high-entropy detectors; a user pattern's match is shown
 * whole, which is the point of the preview.
 */
text: string, context: string, value_follows: boolean, };
