// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transition a scheduled draft launch just made.
 */
export type ScheduledLaunchState = "scheduled" | "cancelled" | "launched" | "failed" | "dead";
