// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `launch_at`: RFC3339, at most 30 days ahead.
 */
export type ScheduleLaunchRequest = { launch_at: string, };
