// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfUpdateTarget } from "./SelfUpdateTarget";

export type SelfUpdateTargetInfo = { 
/**
 * The effective target: stored one first, else the env fallback, else
 * `null` (the button then tells the admin to configure one).
 */
target: SelfUpdateTarget | null, 
/**
 * `"settings"` when it comes from the admin form, `"env"` from
 * `CCTUI_SELF_UPDATE_*`, `null` when unset.
 */
source: string | null, };
