// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelfUpdateTarget } from "./SelfUpdateTarget";

export type SelfUpdateTargetRequest = { 
/**
 * `null` clears the stored target (the env fallback, if any, then applies).
 */
target: SelfUpdateTarget | null, };
