// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the self-update agent runs. Stored under `instance_settings.self_update`.
 */
export type SelfUpdateTarget = { 
/**
 * Enrolled machine (uuid) the update session is spawned on.
 */
machine_id: string, 
/**
 * Working directory of that session; the deployment's checkout or
 * operations folder, whatever the local instructions expect.
 */
working_dir: string, 
/**
 * Adapter to run it under (`claude-code` / `codex`); `None` → claude-code.
 */
adapter_id?: string | null, };
