// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the two paths took the job, and what to watch as a result.
 */
export type SelfUpdateResponse = { "mode": "hook", run_id: string, 
/**
 * Version the machine was asked to deploy.
 */
version: string, } | { "mode": "agent", 
/**
 * Spawn command id, to await on the websocket like a manual spawn.
 */
command_id: string, 
/**
 * The id the new session registers under (claude-code pre-mints it),
 * so the webui can jump to it; `null` for adapters that mint their own.
 */
session_id: string | null, 
/**
 * Version the agent was asked to deploy.
 */
version: string, 
/**
 * Account the spawn bound (see `SpawnResponse::account`).
 */
account: string | null, };
