// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateHookPhase } from "./UpdateHookPhase";

/**
 * A hook run as the webui sees it.
 */
export type SelfUpdateRun = { id: string, machine_id: string, 
/**
 * Version this run is deploying.
 */
version: string, 
/**
 * Version that was running when the run started.
 */
from_version: string, phase: UpdateHookPhase, 
/**
 * Whether the run has finished, either way.
 */
done: boolean, exit_code: number | null, detail: string, 
/**
 * Tail of the hook's output; `null` until a command has produced any.
 */
output_tail: string | null, started_at: string, updated_at: string, };
