// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-side facts merged into the diagnose response (the daemon cannot see
 * its own DB row or the gateway token bindings).
 */
export type ServerDiagnose = { 
/**
 * `sessions.status` (`active`/`ended`/`archived`/…).
 */
status?: string | null, adapter_id?: string | null, 
/**
 * Whether a live (non-revoked) gateway session token binds this session
 * to an account.
 */
account_bound: boolean, 
/**
 * Names of the bound account(s), one per provider family.
 */
accounts: Array<string>, machine_id?: string | null, 
/**
 * `machines.last_seen_at` as unix ms — the daemon heartbeat freshness.
 */
machine_last_seen_ms?: number | null, };
