// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentEvent } from "./AgentEvent";
import type { JsonValue } from "./serde_json/JsonValue";
import type { Session } from "./Session";
import type { SessionStatus } from "./SessionStatus";

export type ServerEvent = { "type": "stream", session_id: string, data: AgentEvent, } | { "type": "status", session_id: string, status: SessionStatus, } | { "type": "session_registered", session: Session, } | { "type": "session_deregistered", session_id: string, } | { "type": "permission_request", session_id: string, request_id: string, tool_name: string, description: string, input_preview: string, } | { "type": "permission_resolved", session_id: string, request_id: string, } | { "type": "ask_question", session_id: string, question: string, questions: JsonValue | null, } | { "type": "ask_resolved", session_id: string, } | { "type": "command_result", command_id: string, ok: boolean, error: string | null, } | { "type": "archive_manifest", machine_id: string, count: number, } | { "type": "archive_uploaded", machine_id: string, project_dir: string, session_id: string, size_bytes: number, sha256: string, };
