// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachStatus } from "./AttachStatus";
import type { CodexDiagnose } from "./CodexDiagnose";
import type { DiagnoseFact } from "./DiagnoseFact";
import type { DispatchStatus } from "./DispatchStatus";
import type { EffectiveState } from "./EffectiveState";
import type { GatewayStatus } from "./GatewayStatus";
import type { HookEvent } from "./HookEvent";
import type { PendingPrompts } from "./PendingPrompts";
import type { PtyOutputStats } from "./PtyOutputStats";
import type { SocketStatus } from "./SocketStatus";
import type { TranscriptStatus } from "./TranscriptStatus";

/**
 * Everything the daemon knows about one session, dated (CCT-547). Assembled
 * by the adapter from state it already tracks — aggregation, not new sensing.
 *
 * The named facts below are the adapter-neutral / claude-code set. Adapters
 * with their own diagnostics attach an optional tagged section (currently
 * [`SessionDiagnose::codex`]); this keeps the claude wire shape stable while
 * letting each adapter carry its own payload (CCT-640).
 */
export type SessionDiagnose = { 
/**
 * The stable session id the server keys on.
 */
local_id: string, 
/**
 * The 8-hex worker shortcode, when resolvable.
 */
short: string | null, 
/**
 * When the daemon assembled this report (unix ms). Ages are relative to
 * this instant.
 */
generated_at_ms: number, adapter: string, 
/**
 * Effective state + arbitration verdict; the fact's `source` says which
 * input produced it (`hook` vs `activity` vs `timeout`).
 */
effective_state: DiagnoseFact<EffectiveState>, last_hook_event: DiagnoseFact<HookEvent>, attach: DiagnoseFact<AttachStatus>, 
/**
 * Held-attach PTY output age/throughput (CCT-546); the second activity
 * signal, hook-independent.
 */
pty_output: DiagnoseFact<PtyOutputStats>, claude_socket: DiagnoseFact<SocketStatus>, transcript: DiagnoseFact<TranscriptStatus>, prompts: DiagnoseFact<PendingPrompts>, 
/**
 * Launch permission posture (`default`/`auto`/`yolo`/`whip`), when the
 * daemon recorded it at spawn time.
 */
permission_mode: DiagnoseFact<string>, dispatch: DiagnoseFact<DispatchStatus>, gateway: DiagnoseFact<GatewayStatus>, 
/**
 * Codex-adapter-specific section (CCT-640); `None` for claude-code.
 */
codex: CodexDiagnose | null, };
