// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an ended session ended — the persisted `sessions.end_reason`.
 *
 * Coarser than [`crate::adapter::EndReason`]: the adapter's free-form detail
 * lives in `end_detail`, and the server adds the reasons no adapter can
 * report (daemon gone, machine offline, aged out by the reaper).
 */
export type SessionEndReason = "completed" | "killed" | "crashed" | "daemon_lost" | "machine_offline" | "reaped_inactive" | "resume_failed" | "other";
