// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `image_id` is referenced as `cctui-img://<image_id>`.
 */
export type SessionImageUploadResponse = { image_id: string, };
