// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reply to `POST /api/v1/daemon/sessions/{id}/images`: the stored
 * blob id the daemon rewrites into a `cctui-img://<image_id>` message marker.
 */
export type SessionImageUploadResponse = { image_id: string, };
