// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state for a session. Three non-terminal states driven by the
 * timestamp of the most recent activity, not by a heartbeat liveness probe:
 *
 * - `New`: session registered, no assistant turn has arrived yet.
 * - `Active`: most recent activity within the active window.
 * - `Inactive`: no recent activity, but the session is not archived — a
 *   new message or turn revives it back to `Active`.
 * - `Archived`: explicitly dismissed (manually or by the TTL reaper).
 *   Hidden from the default list. A genuinely revived session (new
 *   activity) returns to `Active`; an archived dead session stays hidden.
 */
export type SessionStatus = "new" | "active" | "inactive" | "archived";
