// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { Attention } from "./Attention";
import type { Bucket } from "./Bucket";
import type { JsonValue } from "./serde_json/JsonValue";
import type { Liveness } from "./Liveness";
import type { SessionStatus } from "./SessionStatus";
import type { TokenUsage } from "./TokenUsage";

export type SessionListItem = { id: string, parent_id: string | null, machine_id: string, working_dir: string, status: SessionStatus, 
/**
 * Heartbeat-age liveness tier driving the status dot (green/orange/none).
 * Defaults to `Dead` for back-compat with any client that omits it.
 */
liveness: Liveness, 
/**
 * What the session is waiting on, if anything (the ✋ "needs input"
 * glyph). `None` when the session needs no attention.
 */
attention: Attention | null, 
/**
 * Classifier bucket this session falls in (Working / Needs input /
 * Ready for review / Completed). Drives the grouped session list in
 * both clients (CCT-90). Defaults to `Working` for back-compat.
 */
bucket: Bucket, uptime_secs: number, token_usage: TokenUsage, metadata: JsonValue, 
/**
 * Adapter that produced this session. Defaults to `"claude-code"` for
 * legacy rows that pre-date the `sessions.adapter_id` column.
 */
adapter_id: AdapterId | null, 
/**
 * Machine name (resolved from `machine_id`). `None` if the machine row
 * has been deleted but historical sessions still reference it.
 */
machine_name: string | null, 
/**
 * Last message text seen on this session, truncated to ~120 chars.
 */
last_message_text: string | null, 
/**
 * Timestamp of the last message event for this session.
 */
last_message_at: string | null, 
/**
 * User-defined session name, when set (falls back to id in the UI).
 */
name: string | null, 
/**
 * Model the session runs on (e.g. `"opus[1m]"`).
 */
model: string | null, 
/**
 * Reasoning/effort level (e.g. `"low"`, `"high"`), when set.
 */
effort: string | null, 
/**
 * Whether cctui-side auto-approve is on for this session (CCT-151).
 * In-memory server state, reflected so clients can show the toggle.
 */
auto_approve: boolean, };
