// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of a session's active per-family gateway credential bindings.
 */
export type SessionBinding = { family: "anthropic" | "openai" | "fireworks", credential_id: string, account_id: string, account_name: string, };
