// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One recorded mid-session account move.
 */
export type SessionRebind = { id: string, session_id: string, pool_id: string | null, from_account: string, to_account: string, 
/**
 * `pool` or `redirect` — which mechanism moved the session.
 */
reason: string, created_at: string, };
