// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate session counts for the Overview page (`GET /api/v1/sessions/stats`).
 * Computed from full SQL aggregates + the live registry rather than the capped
 * session list, so the numbers stay correct past the list's display limit.
 */
export type SessionStats = { 
/**
 * All sessions, including archived.
 */
total: number, 
/**
 * Sessions currently live in the registry (active or new).
 */
live: number, 
/**
 * Sessions whose classifier bucket is `Blocked` (✋ needs input).
 */
needs_input: number, 
/**
 * Sessions in the sticky `archived` state.
 */
archived: number, };
