// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who started a session's underlying job.
 *
 * `Foreign` is a `claude --bg` (or shell) job the daemon discovered rather
 * than launched: it is driveable like any other, but nothing automatic of
 * ours may attach to, kill or `claude rm` it — only an explicit user removal.
 */
export type SessionOrigin = "fleet" | "foreign";
