// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { SessionStatus } from "./SessionStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type Session = { id: string, parent_id: string | null, account_id: string | null, machine_id: string, working_dir: string, status: SessionStatus, registered_at: string, last_heartbeat: string, metadata: JsonValue, 
/**
 * `None` means claude-code.
 */
adapter_id?: AdapterId | null, };
