// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerDiagnose } from "./ServerDiagnose";
import type { SessionDiagnose } from "./SessionDiagnose";

/**
 * Body of `GET /api/v1/sessions/{id}/diagnose`. Fail-soft: when the daemon
 * round-trip fails (offline, timeout) `daemon` is `None` and `daemon_error`
 * says why; the server facts are still served.
 */
export type SessionDiagnoseResponse = { session_id: string, daemon: SessionDiagnose | null, daemon_error: string | null, server: ServerDiagnose, };
