// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `enabled: false` clears the schedule; omitted fields use provider defaults.
 */
export type SessionKeepaliveRequest = { enabled: boolean, interval_secs?: number | null, max_ticks?: number | null, };
