// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionAttachment = { id: string, session_id: string, message_id: string | null, name: string, hash: string, size: number, content_type: string | null, created_at: number, 
/**
 * The session's machine, once it has registered: what the webui needs to
 * fall back to the staged copy through `/machines/{id}/fs/file`.
 */
machine_id: string | null, };
