// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session counts from SQL aggregates, not the capped list.
 */
export type SessionStats = { 
/**
 * Includes archived.
 */
total: number, live: number, needs_input: number, archived: number, 
/**
 * Registered in local calendar periods, including archived.
 */
today: number, yesterday: number, 
/**
 * Since Monday, local.
 */
week: number, month: number, };
