// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterId } from "./AdapterId";
import type { SessionStatus } from "./SessionStatus";
import type { JsonValue } from "./serde_json/JsonValue";

export type Session = { id: string, parent_id: string | null, account_id: string | null, machine_id: string, working_dir: string, status: SessionStatus, registered_at: string, last_heartbeat: string, metadata: JsonValue, 
/**
 * Adapter that produced this session (e.g. `"claude-code"`, `"codex"`).
 * Optional in the wire shape for back-compat with rows persisted before
 * the `adapter_id` column was added; v0 server fills with `"claude-code"`
 * for legacy rows so this is always populated in fresh data.
 */
adapter_id?: AdapterId | null, };
