// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetAclsRequest = { 
/**
 * The full desired scope set (replaces the existing rows). Strings from the
 * `read|dispatch|enroll|admin` set; unknown values are rejected.
 */
scopes: Array<string>, };
