// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `POST /api/v1/sessions/{id}/set-model` — change the model and/or
 * reasoning effort of a running session in place (CCT-303). At least one of
 * `model`/`effort` should be set; an empty string clears nothing (the field
 * is simply omitted from the adapter command when `None`).
 */
export type SetModelRequest = { model: string | null, effort: string | null, };
