// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `None` fields are left unchanged.
 */
export type SetModelRequest = { model?: string | null, effort?: string | null, };
