// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body of `PUT /machines/{machine_id}/adapters/{adapter}`. An absent field
 * keeps the stored value; a fresh row starts enabled with `{}`.
 */
export type SetMachineAdapterRequest = { enabled?: boolean, config?: Record<string, unknown> | null, };
