// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type SettingsPayload = { version: number, data: JsonValue, 
/**
 * Opaque marker of the stored row this copy was read from. A `PUT` carrying
 * one is refused with `409` once another write has landed since.
 */
revision?: string, };
