// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Policy } from "./Policy";
import type { Source } from "./Source";

/**
 * A single `settings.json` top-level key, enriched from the schema where possible.
 */
export type SettingKey = { 
/**
 * Top-level key name (e.g. `"model"`, `"disableBundledSkills"`).
 */
name: string, 
/**
 * Exposure policy tag.
 */
tag: Policy, 
/**
 * Schema vs docs origin.
 */
source: Source, 
/**
 * JSON type(s), e.g. `"boolean"`, `"string"`, `"array"` (best-effort).
 */
type: string | null, 
/**
 * Allowed enum values, comma-joined, when the key is an enum.
 */
enum: string | null, 
/**
 * Documented default, as a display string.
 */
default: string | null, 
/**
 * Human-readable notes (from the schema description or the hand catalog).
 */
notes: string | null, 
/**
 * Editor grouping for the account-settings toggle list. Set in
 * catalog.toml on the curated boolean keys only; a key with a group gets a
 * tri-state toggle in the webui, everything else is raw-JSON-only.
 */
group: string | null, 
/**
 * Human-readable toggle label (paired with `group`).
 */
label: string | null, };
