// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvVar } from "./EnvVar";
import type { Preset } from "./Preset";
import type { SettingKey } from "./SettingKey";

/**
 * The settings catalog as served to the webui account-settings editor
 * (CCT-571). Everything here comes from the embedded catalog — the webui
 * carries NO mirror of the key list, so it cannot drift from the server that
 * validates the writes. `managed`/`system` keys are omitted entirely.
 */
export type SettingsCatalogResponse = { 
/**
 * Exposable (safe/care) `settings.json` keys, catalog order. Keys with a
 * `group`/`label` are the curated boolean toggles; the rest are settable
 * via the raw-JSON box only.
 */
keys: Array<SettingKey>, 
/**
 * The curated env-var allowlist (all exposable by construction).
 */
env: Array<EnvVar>, 
/**
 * The "Quiet defaults" preset, with its `settings` filtered to exposable
 * keys (the server-applied MANAGED keys are not offerable per-account).
 */
preset: Preset, };
