// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One independent reason a session can look silent.
 *
 * Each variant carries the numbers its message needs; the client owns the
 * wording.
 */
export type SilenceReason = { "kind": "codex_stalled_rpc", count: number, age_ms: number, } | { "kind": "codex_shared_dropped", count: number, age_ms: number, } | { "kind": "codex_shared_no_frames" } | { "kind": "codex_no_turn" } | { "kind": "codex_auth", state: string, } | { "kind": "codex_registry_mismatch", detail: string, } | { "kind": "codex_not_live" } | { "kind": "opencode_sse_down" } | { "kind": "opencode_sse_stalled", age_ms: number, } | { "kind": "opencode_sse_no_frames" } | { "kind": "opencode_http_errors", count: number, age_ms: number, message: string, } | { "kind": "opencode_awaiting_permission", count: number, } | { "kind": "opencode_idle" } | { "kind": "opencode_version", version: string, pinned: string, } | { "kind": "opencode_not_live" };
