// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnchorError } from "./AnchorError";

/**
 * A draft comment left out because it no longer anchors.
 */
export type SkippedComment = { comment_id: string, path: string, line: number, reason: AnchorError, };
