// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which `claude daemon` control socket discovery picked, and whether it
 * answered a live probe.
 */
export type SocketStatus = { 
/**
 * The live socket path, `None` when no candidate answered.
 */
path?: string | null, live: boolean, 
/**
 * Every candidate `control.sock` discovery enumerated.
 */
candidates: Array<string>, };
