// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One window's independently editable soft-limit config. All fields optional:
 * no `cap_pct`/`cap_usd` ⇒ no cap on that window; `bypass_minutes` `None` ⇒ no
 * bypass. `cap_usd` applies to the dollar windows, `cap_pct` to the percent
 * ones; a window is evaluated against whichever its usage reports.
 */
export type SoftLimitConfig = { 
/**
 * Max % of the window cctui will consume before refusing more inference.
 */
cap_pct?: number | null, 
/**
 * Max USD cctui will spend in the window before refusing more inference.
 */
cap_usd?: number | null, 
/**
 * If the window's `resets_at` is within this many minutes, ignore its cap.
 */
bypass_minutes?: number | null, 
/**
 * Max burn rate as a multiple of the window's linear budget: `1.5` refuses
 * once the window is spent 50% faster than evenly. Percent windows only.
 */
pace_cap?: number | null, };
