// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpawnResponse = { command_id: string, status: string, 
/**
 * `None` when unbound.
 */
account?: string | null, 
/**
 * Pre-minted id, when the adapter accepts one.
 */
session_id?: string | null, };
