// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a spawn asks for by way of reusable context.
 *
 * `auto` adds every scope-matching memory on top of the explicit picks. It
 * defaults to OFF: until the spawn panel can show what a scope would pull
 * in, a session gets context only when someone named it.
 */
export type SpawnContext = { 
/**
 * Item names, any kind.
 */
items: Array<string>, auto: boolean, };
