// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The spawn configuration remembered for one target. Mirrors the fields the
 * spawn form recalls; `account_provider` is carried for display only, the form
 * recomputes it from the account.
 */
export type SpawnMemoryEntry = { adapter_id: string, model_claude: string, model_codex: string, model_account: string, effort_claude: string, effort_codex: string, account: string, account_provider: string, permission_mode: string, name: string, labels?: Array<string> | null, 
/**
 * The spawn profile the configuration came from, when it came from one.
 */
profile_id?: string | null, 
/**
 * Last-write time, epoch milliseconds. Drives LRU eviction and the
 * "latest directory on this machine" recall.
 */
at: number, };
