// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Default `CctuiAgent` limits; `null` fields are unset at that layer, and an
 * unset `max_children` or `max_tree_budget_usd` in `effective` means unlimited.
 */
export type SpawnDefaults = { max_children: number | null, max_depth: number | null, max_tree_budget_usd: number | null, };
