// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpawnDefaults } from "./SpawnDefaults";
import type { SpawnDefaultsSources } from "./SpawnDefaultsSources";

export type SpawnDefaultsInfo = { 
/**
 * The values new sessions get; `null` = unlimited.
 */
effective: SpawnDefaults, sources: SpawnDefaultsSources, settings: SpawnDefaults, env: SpawnDefaults, defaults: SpawnDefaults, };
