// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpawnContext = { 
/**
 * Item names, any kind.
 */
items?: Array<string>, auto?: boolean, };
