// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type SpawnRequest = { machine_id: string, working_dir: string, prompt: string | null, prompt_name: string | null, 
/**
 * Optional session display name, launched via the adapter (claude `--name`).
 */
name: string | null, 
/**
 * Adapter to spawn under. Defaults to `"claude-code"` when omitted.
 */
adapter_id: string | null, 
/**
 * Per-spawn permission posture (CCT-149): `yolo` skips all prompts +
 * sandbox, `auto` auto-applies without prompts but keeps the sandbox,
 * `ask` prompts on every action. `None` → the daemon's per-host
 * default. See [`cctui_proto::adapter::PermissionMode`].
 */
permission_mode: PermissionMode | null, 
/**
 * Reasoning/effort level to launch the session with (claude `--effort`,
 * codex `model_reasoning_effort`). Valid values differ per adapter
 * (claude: `low`/`medium`/`high`/`xhigh`/`max`; codex:
 * `minimal`/`low`/`medium`/`high`). `None` → the adapter's default.
 */
effort: string | null, };
