// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpawnMemoryEntry } from "./SpawnMemoryEntry";

/**
 * `GET`/`PUT /api/v1/spawn-memory` — the whole map, keyed by target.
 */
export type SpawnMemoryPayload = { entries: { [key in string]: SpawnMemoryEntry }, };
