// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingSource } from "./SettingSource";

export type SpawnDefaultsSources = { max_children: SettingSource, max_depth: SettingSource, max_tree_budget_usd: SettingSource, };
