// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type SpawnRequest = { machine_id: string, working_dir: string, prompt: string | null, prompt_name: string | null, name?: string | null, 
/**
 * Defaults to `claude-code`.
 */
adapter_id?: string | null, 
/**
 * `None` = the daemon's per-host default.
 */
permission_mode?: PermissionMode | null, 
/**
 * Adapter-specific level. `None` = adapter default.
 */
effort?: string | null, 
/**
 * Model or family alias. `None` = adapter default.
 */
model?: string | null, 
/**
 * Codex only: `fast` or `default`. `None` = the account's setting.
 */
service_tier?: string | null, 
/**
 * Keys match `^[A-Z_][A-Z0-9_]*$`. Never persisted or logged.
 */
env?: { [key in string]: string }, 
/**
 * Account from the caller's vault to route through the gateway.
 */
account?: string | null, 
/**
 * Disambiguates `account` across providers. `None` = derived from the adapter.
 */
provider?: string | null, 
/**
 * Run on the machine's ambient login. Ignored when `account` is set.
 */
no_account?: boolean, 
/**
 * Pick the matching account with the most allocation left instead of
 * rejecting an ambiguous choice. Ignored when `account` or `no_account` is set.
 */
auto_account?: boolean, 
/**
 * Pick among this pool's members only. Ignored when `account` or `no_account` is set.
 */
pool?: string | null, 
/**
 * Persist as a draft without dispatching; `env` is not stored.
 */
save_draft?: boolean, 
/**
 * Archive once the first turn ends cleanly.
 */
auto_archive?: boolean, 
/**
 * Draft only: env var names, values are never stored.
 */
env_keys?: Array<string>, 
/**
 * Draft only.
 */
attachment_names?: Array<string>, 
/**
 * Attached when the worker registers.
 */
label_ids?: Array<string>, 
/**
 * `followup`: the first prompt embeds the parent's brief. `None` = root.
 */
relation?: string | null, parent_session_id?: string | null, };
