// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionMode } from "./PermissionMode";

export type SpawnRequest = { machine_id: string, working_dir: string, prompt: string | null, prompt_name: string | null, 
/**
 * Optional session display name, launched via the adapter (claude `--name`).
 */
name: string | null, 
/**
 * Adapter to spawn under. Defaults to `"claude-code"` when omitted.
 */
adapter_id: string | null, 
/**
 * Per-spawn permission posture (CCT-149): `yolo` skips all prompts +
 * sandbox, `auto` auto-applies without prompts but keeps the sandbox,
 * `ask` prompts on every action. `None` → the daemon's per-host
 * default. See [`cctui_proto::adapter::PermissionMode`].
 */
permission_mode: PermissionMode | null, 
/**
 * Reasoning/effort level to launch the session with (claude `--effort`,
 * codex `model_reasoning_effort`). Valid values differ per adapter
 * (claude: `low`/`medium`/`high`/`xhigh`/`max`; codex:
 * `minimal`/`low`/`medium`/`high`). `None` → the adapter's default.
 */
effort: string | null, 
/**
 * Model family to launch under (CCT-274). Passed to claude as `--model`
 * and to codex as `-c model="…"`. Free-form (the adapter resolves family
 * aliases like `opus`/`sonnet`/`haiku`/`fable`); `None` → the adapter's
 * own default model.
 */
model: string | null, 
/**
 * Environment secrets to inject into the worker process env at spawn time
 * (CCT-202). Keys must match `^[A-Z_][A-Z0-9_]*$`. Carried to the runtime
 * like a bearer capability: NEVER persisted, NEVER logged, NEVER written to
 * the transcript/timeline. `Debug` redacts the values.
 */
env: { [key in string]?: string }, 
/**
 * Named OAuth account to run the session under (CCT-232). Resolved against
 * the caller's own vault; the server mints a session-scoped gateway token
 * and injects `ANTHROPIC_BASE_URL`/`ANTHROPIC_AUTH_TOKEN` (or the codex
 * equivalents) into `env` so the worker's traffic flows through the
 * passthrough gateway under that account. `None` → no gateway injection.
 */
account: string | null, 
/**
 * Provider of the selected `account` (CCT-399): `anthropic` |
 * `anthropic-compatible` | `openai` | `openai-compatible`. Disambiguates a
 * name shared across providers so the account drives the base URL + family
 * unambiguously (instead of inferring the family from `adapter_id`). `None`
 * → fall back to the adapter-derived family.
 */
provider: string | null, 
/**
 * Explicit unbound spawn (CCT-582): when true the server does NOT resolve a
 * default account for an empty `account` — the worker runs on the machine's
 * own ambient login (no gateway env, no session token). This is distinct
 * from an unset `account`, which auto-binds the caller's single
 * matching-family account (CCT-574). Ignored when `account` names an
 * account (a named account always binds).
 */
no_account: boolean, 
/**
 * Stage this spawn as a draft instead of dispatching it (CCT-394). When
 * true the server validates + persists a `draft` session row carrying the
 * spawn payload in `metadata.draft` and does NOT mint account env or
 * dispatch to the daemon. A later `POST /sessions/{id}/launch` mints env
 * fresh and dispatches the real spawn. `env` is ignored for a draft (no
 * secrets at rest — re-entered at launch time).
 */
save_draft: boolean, };
