// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpawnResponse = { command_id: string, status: string, 
/**
 * Account the spawn bound (CCT-582), surfaced so the client can show which
 * credential is in play — chiefly for an auto-bound default the user never
 * named. `None` for an unbound spawn.
 */
account: string | null, };
