// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpeechConfig } from "./SpeechConfig";

export type SpeechSettingsRequest = { config: SpeechConfig, 
/**
 * A new key to store; `null` keeps the current one.
 */
api_key?: string, 
/**
 * Drops the stored key.
 */
clear_key?: boolean, };
