// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingSource } from "./SettingSource";
import type { SpeechConfig } from "./SpeechConfig";

export type SpeechSettingsInfo = { config: SpeechConfig, 
/**
 * Whether an API key is stored; the key itself is never returned.
 */
has_key: boolean, 
/**
 * `settings` once an admin saved a value, else `default`.
 */
source: SettingSource, };
