// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Non-secret part of the `speech` instance setting.
 */
export type SpeechConfig = { enabled: boolean, 
/**
 * OpenAI-compatible root, e.g. `https://speech.example/v1`.
 */
base_url: string, stt_model: string, stt_language: string | null, tts_model: string, tts_voice: string, tts_format: string, };
