// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response to `POST /api/v1/sessions/{id}/files` (mid-chat
 * attachments).
 *
 * The staged absolute paths on the session's machine, in the same order the
 * files were uploaded. The webui appends these under the reply prompt so the
 * agent reads them — the same convention as spawn-time uploads.
 */
export type StageFilesResponse = { paths: Array<string>, };
