// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Absolute paths on the session's machine, in upload order.
 */
export type StageFilesResponse = { paths: Array<string>, };
