// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserActionStatus } from "./UserActionStatus";

/**
 * Body for `POST /api/v1/daemon/sessions/{id}/user-actions/tick`.
 */
export type TickUserActionRequest = { 
/**
 * A string, not a `Uuid`: a model that invents an id must get the list back
 * with a readable reason, not a deserialization failure.
 */
id: string, status: UserActionStatus, note?: string | null, };
