// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task-list entry. `status` is `pending`, `in_progress` or `completed`;
 * `active_form` is claude-only.
 */
export type TodoEntry = { content: string, status: string, active_form?: string | null, };
