// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowTokenUsage } from "./WindowTokenUsage";

/**
 * Aggregate token usage across rolling time windows for the Overview page.
 *
 * `today` is calendar-day (since local midnight, derived from the caller's
 * timezone offset); the others are rolling intervals back from now.
 */
export type TokenUsageWindows = { 
/**
 * Last 60 minutes.
 */
hour: WindowTokenUsage, 
/**
 * Since local midnight.
 */
today: WindowTokenUsage, 
/**
 * Last 24 hours.
 */
day: WindowTokenUsage, 
/**
 * Last 7 days.
 */
week: WindowTokenUsage, 
/**
 * Last 30 days.
 */
month: WindowTokenUsage, };
