// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WindowTokenUsage } from "./WindowTokenUsage";

/**
 * `today` is since local midnight; the rest are rolling.
 */
export type TokenUsageWindows = { hour: WindowTokenUsage, today: WindowTokenUsage, day: WindowTokenUsage, week: WindowTokenUsage, month: WindowTokenUsage, };
