// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The stored, editable form of an account's policy.
 */
export type ToolPolicy = { 
/**
 * Case-insensitive literals.
 */
terms: Array<string>, 
/**
 * Case-insensitive regular expressions.
 */
patterns: Array<string>, 
/**
 * GitHub owners whose `owner/repo#n` references and PR/issue URLs are
 * blocked.
 */
protected_owners: Array<string>, 
/**
 * Sessions whose cwd is under one of these roots are not scanned.
 */
exempt_roots: Array<string>, };
