// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A retained stderr line from the harness process, secret-redacted.
 */
export type TrafficStderrLine = { ts_ms: number, line: string, };
