// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One protocol error (`<label>: <error>`), secret-redacted.
 */
export type TrafficError = { ts_ms: number, message: string, 
/**
 * Which transport the error was observed on.
 */
transport: string, };
