// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One retained protocol frame, secret-redacted and truncated to 2 KiB.
 */
export type TrafficFrame = { ts_ms: number, 
/**
 * `out` (daemon → harness) or `in` (harness → daemon).
 */
direction: string, 
/**
 * What the frame is: a JSON-RPC `method`/`id` for codex, an
 * `METHOD /path` or SSE event type for opencode.
 */
label: string, json: string, 
/**
 * Which transport carried the frame. Codex: `stdio` (the per-session
 * app-server child) or `shared` (the process-wide app-server socket).
 * `OpenCode`: `http` (the request/response API) or `sse` (`GET /event`).
 */
transport: string, };
