// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TuiCommand = { "type": "subscribe", session_id: string, } | { "type": "unsubscribe", session_id: string, } | { "type": "message", session_id: string, content: string, client_msg_id: string | null, } | { "type": "permission_response", session_id: string, request_id: string, behavior: string, };
