// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewVerdict } from "./ReviewVerdict";

/**
 * Patch body for `PATCH .../drafts/{draft_id}` — change the verdict.
 */
export type UpdateReviewDraft = { verdict: ReviewVerdict, };
