// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request body for `PATCH /api/v1/github/connectors/{id}`.
 *
 * Every field is optional: only the present ones are changed (rename, re-scope
 * repos, rotate the credential, set/clear the webhook secret). A `credential`
 * is only re-encrypted when present and non-empty — omit it to keep the stored
 * one. Rotating the credential clears the cached `viewer_login` so the next
 * poll re-resolves it against the new token.
 */
export type UpdateConnector = { 
/**
 * New human-readable label, if renaming.
 */
name: string | null, 
/**
 * Replacement set of `owner/name` slugs, if re-scoping. Replaces the whole
 * list (not merged); an empty list tracks every repo the token can see.
 */
repos: Array<string> | null, 
/**
 * A replacement credential to rotate to. Omitted/empty = keep the current.
 */
credential: string | null, 
/**
 * Webhook secret: `Some(non-empty)` sets it, `Some("")` clears it, `None`
 * leaves it unchanged.
 */
webhook_secret: string | null, };
