// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a hook run got to.
 *
 * The happy path is `Running` → `Verifying` → `Succeeded`. Any failure goes
 * to `RollingBack` → `RolledBack` when a rollback command is configured, and
 * straight to `Failed` when none is (or when the rollback itself failed).
 */
export type UpdateHookPhase = "running" | "verifying" | "succeeded" | "rolling_back" | "rolled_back" | "failed";
