// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountModel } from "./AccountModel";
import type { RateLimits } from "./RateLimits";
import type { SoftLimitConfig } from "./SoftLimitConfig";
import type { UsageNotices } from "./UsageNotices";

/**
 * `PATCH /api/v1/accounts/{id}/providers/{provider_id}` payload. A partial update:
 * for a non-managed compatible endpoint the operator may edit `base_url`,
 * `auth_scheme`, and rotate the static credential (`access_token`).
 * `models` / `model_aliases` / `soft_limits` / `settings_json` are editable
 * for every provider. All optional; an absent field leaves that column unchanged.
 * `base_url`/credential are never returned, so the editor re-supplies
 * `base_url` when changing it and leaves the credential blank to keep the
 * stored one.
 */
export type UpdateProvider = { base_url?: string, auth_scheme?: string, models?: Array<AccountModel>, 
/**
 * Replacement model alias map. Provided → replaces the stored map
 * wholesale (an empty object clears it); absent → unchanged.
 */
model_aliases?: Record<string, string>, 
/**
 * New static credential for a compatible endpoint; blank/absent keeps the
 * stored one.
 */
access_token?: string, 
/**
 * Replacement soft-limit config: a canonical-key map
 * `{ key: {cap_pct?, bypass_minutes?, pace_cap?} }`. Provided → replaces the whole
 * stored map (an empty object clears it, an omitted key drops that window);
 * absent → unchanged. Validated before persist.
 */
soft_limits?: { [key in string]: SoftLimitConfig }, 
/**
 * Replacement usage ticker `{ enabled?, step_pct? }`. Provided → replaces
 * (an empty object / `enabled: false` turns it off); absent → unchanged.
 */
usage_notices?: UsageNotices, 
/**
 * Show this credential's gauge in the header strip; absent → unchanged.
 */
header_pin?: boolean, 
/**
 * Replacement validated settings blob. Provided → replaces the
 * stored settings wholesale (an empty object clears it); absent → unchanged.
 * Validated against the allowlist before persist.
 */
settings_json?: Record<string, unknown>, 
/**
 * Replacement gateway settings object. Provided → replaces wholesale (an
 * empty object drops back to the family defaults); absent → unchanged.
 */
provider_settings?: Record<string, unknown>, 
/**
 * Replacement rate-limit object `{ rpm?, tpm? }`. Provided → replaces the
 * stored value (an empty object / zeros clear it); absent → unchanged.
 */
rate_limits?: RateLimits, };
