// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Partial update of a user (CCT-185). Any field left `None` is unchanged, so
 * the same endpoint serves both rename and the dispatch-permission toggle.
 */
export type UpdateUserRequest = { 
/**
 * Blank/whitespace is rejected (name is `NOT NULL`); `None` leaves it.
 */
name: string | null, can_dispatch: boolean | null, 
/**
 * `true` sets `disabled_at = now()`, `false` clears it (CCT-251).
 */
disabled: boolean | null, };
