// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH /api/v1/accounts/{id}` payload: identity-level fields only.
 * `name` renames; `env_json` provided → re-encrypts and replaces (an empty map
 * clears it); absent → unchanged (write-only, never returned). The legacy
 * provider-ish fields are accepted syntactically but rejected with a pointer
 * to the provider route, so an un-migrated client gets a clear 400 instead of
 * a silent no-op.
 */
export type UpdateAccount = { name?: string, 
/**
 * Identity glyph. A blank string clears it back to the letter square;
 * absent leaves it unchanged.
 */
emoji?: string, env_json?: Record<string, string>, 
/**
 * Names to remove from the stored env without re-sending the other
 * values: decrypt → drop names → re-encrypt, all server-side. Ignored
 * when `env_json` is provided (replace-all wins).
 */
env_remove?: string[], 
/**
 * Owner-only: whether grantees may enrol this account in their pools.
 */
pool_eligible?: boolean, 
/**
 * Owner-only: the account's relative plan size in pool aggregates. Must
 * be a finite positive number.
 */
pool_weight?: number, };
