// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `PATCH /api/v1/github/connectors/{id}`; absent fields are unchanged.
 * Rotating the credential clears the cached viewer login.
 */
export type UpdateConnector = { name: string | null, 
/**
 * Replaces the whole list; empty tracks every repo the token can see.
 */
repos: Array<string> | null, 
/**
 * Omitted or empty keeps the current one.
 */
credential: string | null, 
/**
 * `Some("")` clears it, `None` leaves it unchanged.
 */
webhook_secret: string | null, };
