// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdatePoolRequest = { name?: string, strategy?: string, failover?: boolean, 
/**
 * Absent leaves the membership alone; present replaces it wholesale, in
 * the given order.
 */
accounts?: string[] | null, };
