// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Body for `PATCH /api/v1/labels/{id}` — rename and/or recolor an existing
 * label by id. Either field may be omitted to leave it unchanged.
 */
export type UpdateLabelRequest = { name?: string | null, color?: string | null, };
