// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `PATCH` payload — title and note only; the snapshot itself is immutable.
 */
export type UpdateBookmark = { title: string | null, note: string | null, };
