// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileSpec } from "./ProfileSpec";

/**
 * Every field optional; the spec, when present, replaces the whole kit (the
 * panel always holds the full one), so a cleared knob really clears.
 */
export type UpdateProfileRequest = { name?: string, spec?: ProfileSpec, };
