// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Patch body for `PATCH .../drafts/{draft_id}/comments/{comment_id}` — edit the
 * body of an existing draft comment in place (the anchor is immutable).
 */
export type UpdateDraftComment = { body: string, };
