// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateHookPhase } from "./UpdateHookPhase";

/**
 * One progress report from the daemon about a hook run, the body of
 * `POST /api/v1/daemon/update-hook/{run_id}`.
 */
export type UpdateHookReport = { phase: UpdateHookPhase, 
/**
 * Exit status of the command this phase ran, once it has exited.
 */
exit_code: number | null, 
/**
 * One line for the UI: what just happened, in plain words.
 */
detail: string, 
/**
 * Tail of the merged stdout/stderr, capped at [`OUTPUT_TAIL_BYTES`].
 */
output_tail?: string | null, };
