// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UploadCaps = { max_files: number, max_file_bytes: number, max_total_bytes: number, };
