// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadCaps } from "./UploadCaps";

export type UploadCapsRequest = { 
/**
 * `null` clears the saved caps, restoring the built-in defaults.
 */
caps: UploadCaps | null, };
