// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingSource } from "./SettingSource";
import type { UploadCaps } from "./UploadCaps";

export type UploadCapsInfo = { effective: UploadCaps, defaults: UploadCaps, 
/**
 * `settings` once an admin saved a value, else `default`.
 */
source: SettingSource, 
/**
 * The router's boot-time ceiling; a saved total cap must stay under it.
 */
body_limit_bytes: number, 
/**
 * Env var that sets `body_limit_bytes` (restart required).
 */
body_limit_env: string, };
