// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpstreamHostsRequest = { 
/**
 * `null` clears the saved list; env and managed hosts stay allowed.
 */
hosts: Array<string> | null, };
