// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingSource } from "./SettingSource";

export type UpstreamHostsInfo = { 
/**
 * The effective editable list.
 */
hosts: Array<string>, source: SettingSource, 
/**
 * The `CCTUI_UPSTREAM_ALLOWED_HOSTS` seed.
 */
env: Array<string>, 
/**
 * Always allowed on top of `hosts` (the `LiteLLM` endpoint).
 */
managed: Array<string>, };
