// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpstreamHostsRequest = { 
/**
 * `null` resets to the env seed / default.
 */
hosts: Array<string> | null, };
