// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingSource } from "./SettingSource";

export type UpstreamHostsInfo = { 
/**
 * The saved, editable entries.
 */
hosts: Array<string>, 
/**
 * `settings` once a list has been saved, else `default`.
 */
source: SettingSource, 
/**
 * `CCTUI_UPSTREAM_ALLOWED_HOSTS`, always allowed on top of `hosts`.
 */
env: Array<string>, 
/**
 * Always allowed on top of `hosts` (the `LiteLLM` endpoint).
 */
managed: Array<string>, };
