// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeatmapCell } from "./HeatmapCell";
import type { ModelUsage } from "./ModelUsage";
import type { UsageBucket } from "./UsageBucket";

export type UsageAnalytics = { 
/**
 * `hour` or `day`.
 */
granularity: string, 
/**
 * Oldest first.
 */
buckets: Array<UsageBucket>, 
/**
 * By output tokens, descending.
 */
models: Array<ModelUsage>, heatmap: Array<HeatmapCell>, };
