// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pace of one window relative to its linear budget.
 */
export type UsagePace = { 
/**
 * 0..1: share of the window already elapsed.
 */
elapsed_fraction: number, 
/**
 * Utilization a perfectly even spend would show now (`elapsed_fraction * 100`).
 */
expected_pct: number, 
/**
 * `utilization / expected_pct` — < 1 under pace, > 1 burning too fast.
 */
ratio: number, 
/**
 * When utilization reaches 100% at the current rate; `None` when idle.
 */
projected_wall_at?: string | null, 
/**
 * Length, in hours, of the base the rate was measured over when it came
 * from an earlier sample; `None` when the rate is the window average.
 */
slope_hours?: number | null, };
