// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HeatmapCell } from "./HeatmapCell";
import type { ModelUsage } from "./ModelUsage";
import type { UsageBucket } from "./UsageBucket";

/**
 * Overview usage analytics: tokens-over-time buckets, per-model
 * breakdown, and an activity heatmap — one endpoint, one round-trip set for
 * the whole Overview usage section.
 */
export type UsageAnalytics = { 
/**
 * Bucket granularity: `"hour"` for short ranges, else `"day"`.
 */
granularity: string, 
/**
 * Tokens-over-time buckets, ordered oldest→newest.
 */
buckets: Array<UsageBucket>, 
/**
 * Per-model breakdown, ordered by output-token volume (desc).
 */
models: Array<ModelUsage>, 
/**
 * Sparse hour-of-week activity cells.
 */
heatmap: Array<HeatmapCell>, };
