// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `{ "enabled": bool, "step_pct": int }` on the provider row. NULL ⇒ off.
 */
export type UsageNotices = { enabled: boolean, step_pct: number, };
