// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageHistorySample } from "./UsageHistorySample";

export type UsageHistory = { account_id: string, samples: Array<UsageHistorySample>, };
