// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Missing buckets are zero-filled client-side.
 */
export type UsageBucket = { 
/**
 * Bucket start, RFC3339 UTC.
 */
bucket: string, input: number, output: number, cache_read: number, cache_creation: number, };
