// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageHistorySample = { window_key: string, utilization: number, amount_usd: number | null, resets_at: string | null, sampled_at: string, source: string, };
