// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A quota probe the server's registry serves, for the `usage_probe` picker.
 */
export type UsageProbeInfo = { id: string, label: string, };
