// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One time bucket of aggregate token usage for the Overview usage chart.
 *
 * (.) `bucket` is the `date_trunc`'d instant (RFC3339, in the fixed
 * reporting timezone anchored by the caller's `tz_offset`, mapped back to a
 * UTC instant like `today` in [`TokenUsageWindows`]). Missing buckets are
 * zero-filled client-side, not in SQL.
 */
export type UsageBucket = { 
/**
 * Start of the bucket as an RFC3339 UTC instant.
 */
bucket: string, 
/**
 * Non-cached prompt tokens summed over the bucket.
 */
input: number, 
/**
 * Generated tokens summed over the bucket.
 */
output: number, 
/**
 * Prompt-cache read tokens (⚡) summed over the bucket.
 */
cache_read: number, 
/**
 * Prompt-cache creation tokens summed over the bucket.
 */
cache_creation: number, };
