// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One normalized usage window, provider-agnostic and self-describing.
 */
export type UsageWindow = { 
/**
 * Stable canonical identity (`session` / `weekly_all` / `weekly_model:<id>`).
 */
key: string, 
/**
 * Forward-compatible kind: `session` | `weekly_all` | `weekly_scoped` | other.
 */
kind: string, 
/**
 * Human display label (`5h`, `Weekly (all models)`, `Weekly Fable`, …).
 */
label: string, 
/**
 * Utilization percent (0–100, may exceed on overage). `0` for a dollar
 * window with no cap to measure against.
 */
utilization: number, 
/**
 * USD spent in the window; set only for the dollar windows.
 */
amount_usd?: number | null, 
/**
 * When the window resets (rfc3339 upstream), if known.
 */
resets_at?: string | null, 
/**
 * Stable upstream model id for a scoped window, if any.
 */
model_id?: string | null, 
/**
 * Model display name for a scoped window, if any.
 */
model_display_name?: string | null, };
