// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageWindowClose = { account_id: string, window_key: string, resets_at: string, final_utilization: number, wasted_pct: number, closed_at: string, source: string, };
