// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageWindowClose } from "./UsageWindowClose";
import type { WastedSummary } from "./WastedSummary";

export type UsageWindowCloses = { closes: Array<UsageWindowClose>, summary: Array<WastedSummary>, };
