// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserTokenRow = { id: string, label: string | null, created_at: string, expires_at: string | null, revoked_at: string | null, 
/**
 * Non-secret fragment for display (CCT-185), e.g. `cctui_u_ab12…ef34`.
 * `None` for tokens minted before the preview column existed.
 */
token_preview: string | null, };
