// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAclsResponse = { user_id: string, 
/**
 * The user's ceiling (what its keys may be granted), as scope strings.
 */
scopes: Array<string>, };
