// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRow = { id: string, name: string, created_at: string, revoked_at: string | null, };
