// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserTokenRow = { id: string, label: string | null, created_at: string, expires_at: string | null, revoked_at: string | null, };
