// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the agent needs from the user.
 */
export type UserActionKind = "action" | "input" | "decision";
