// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Open user-action counts for a session card. `child_*` rolls up the session's
 * subagents, so a parent sees that a child is blocked on the user.
 */
export type UserActionCounts = { open: number, blocking: number, child_open: number, child_blocking: number, };
