// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserActionKind } from "./UserActionKind";
import type { UserActionResolver } from "./UserActionResolver";
import type { UserActionStatus } from "./UserActionStatus";

/**
 * One thing the agent is waiting on from the user.
 */
export type UserAction = { id: string, title: string, detail?: string | null, kind: UserActionKind, blocking: boolean, status: UserActionStatus, note?: string | null, created_at: string, resolved_at?: string | null, resolved_by?: UserActionResolver | null, };
