// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who resolved an item. The agent must see the user's own ticks, so this is
 * recorded rather than assumed.
 */
export type UserActionResolver = "agent" | "user";
