// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserAction } from "./UserAction";

/**
 * A session's whole list. Every mutation returns it, so the caller — model or
 * browser — never has to reconstruct the state it did not cause.
 */
export type UserActionList = { session_id: string, items: Array<UserAction>, };
