// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VersionInfo = { version: string, git_hash: string, repo_url: string, commit_url: string, 
/**
 * Newest upstream release, present **only** when strictly newer than
 * `version` (see `update_check`). `null` when up to date, when the probe
 * is disabled, or before its first answer.
 */
latest_version: string | null, 
/**
 * Release page for `latest_version`.
 */
latest_url: string | null, 
/**
 * Admin-set deployment label (`PUT /admin/instance`); `null` by default.
 */
instance_name: string | null, };
