// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VersionInfo = { version: string, git_hash: string, repo_url: string, commit_url: string, 
/**
 * Newest upstream release, present **only** when strictly newer than
 * `version` (see `update_check`). `null` when up to date, when the probe
 * is disabled, or before its first answer.
 */
latest_version: string | null, 
/**
 * Release page for `latest_version`.
 */
latest_url: string | null, 
/**
 * Admin-set deployment label (`PUT /admin/instance`); `null` by default.
 */
instance_name: string | null, 
/**
 * Whether an admin can launch a self-update from here: a self-update
 * machine is configured (settings or env). Everyone sees the flag, only
 * admins get the button; the machine itself stays admin-only.
 */
self_update_ready: boolean, 
/**
 * Whether that machine has a deterministic update hook
 * (`CCTUI_UPDATE_COMMAND`), so the update runs the operator's own command
 * instead of a YOLO agent. Drives what the update modal promises.
 */
self_update_hook: boolean, };
