// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One blob-keyed "reviewed" mark for a file in a PR, scoped to the caller.
 */
export type ViewedMarkInfo = { 
/**
 * Head-side file path the mark applies to.
 */
path: string, 
/**
 * The blob SHA the file had when marked reviewed. The webui treats a file
 * as reviewed only while its current `DiffFile.blob_sha` equals this — a
 * later push that changes the file rotates its blob SHA and re-flags it.
 */
blob_sha: string, marked_at: string, };
