// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ViewedMarkInfo = { path: string, 
/**
 * The file counts as reviewed only while its current blob SHA matches.
 */
blob_sha: string, marked_at: string, };
