// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `GET /voice/config`: what the webui may use, without the URL or key.
 */
export type VoiceConfigInfo = { enabled: boolean, stt_model: string, stt_language: string | null, tts_model: string, tts_voice: string, tts_format: string, };
