// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mean unused share of the closed instances of one window key.
 */
export type WastedSummary = { window_key: string, windows: number, mean_wasted_pct: number, };
