// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token totals for one time window, mirroring the three figures the session
 * list shows (`↑in ↓out ⚡cache`).
 *
 * Cache-creation tokens are intentionally
 * omitted here — the Overview surfaces the same readout as the session card.
 */
export type WindowTokenUsage = { 
/**
 * Non-cached prompt tokens (`input_tokens`).
 */
input: number, 
/**
 * Generated tokens (`output_tokens`).
 */
output: number, 
/**
 * Tokens served from the prompt cache (`cache_read_tokens`, the ⚡ figure).
 */
cache_read: number, };
